class CfgRemoteExec
{
	class Functions
	{
		mode = 1;
		jip = 1;
		
		//All
		class life_fnc_broadcast {allowedTargets = 0;};
		class life_fnc_logdat {allowedTargets = 0;};

		//Client
		class life_fnc_fallout {allowedTargets = 1;};
		class life_fnc_ticketAction {allowedTargets = 1;};
		class life_fnc_numberText {allowedTargets = 1;};
		class life_fnc_jail {allowedTargets = 1;};
		class life_fnc_pulloutVeh {allowedTargets = 1;};
		class life_fnc_colorVehicle {allowedTargets = 1;};
		class life_fnc_restrain {allowedTargets = 1;};
		class life_fnc_robReceive {allowedTargets = 1;};
		class life_fnc_robPerson {allowedTargets = 1;};
		class life_fnc_searchClient {allowedTargets = 1;};
		class life_fnc_copSearch {allowedTargets = 1;};
		class life_fnc_setFuel {allowedTargets = 1;};
		class life_fnc_hasOrgan {allowedTargets = 1;};
		class life_fnc_disableUserInput {allowedTargets = 1;};
		class life_fnc_LicenseShown {allowedTargets = 1;};
		class life_fnc_rechnungPrompt {allowedTargets = 1;};
		class life_fnc_RechnungPaid {allowedTargets = 1;};
		class life_fnc_freezePlayer {allowedTargets = 1;};
		class life_fnc_hideit {allowedTargets = 1;};
		class life_fnc_teleportPlayer {allowedTargets = 1;};
		class life_fnc_mailbox {allowedTargets = 1;};
		class life_fnc_crashStart {allowedTargets = 1;};
		class life_fnc_jumpFnc {allowedTargets = 1;};
		class life_fnc_knockedOut {allowedTargets = 1;};
		class life_fnc_breathalyzer {allowedTargets = 1;};
		class life_fnc_licenseCheck {allowedTargets = 1;};
		class life_fnc_licensesRead {allowedTargets = 1;};
		class life_fnc_scheinEntzugNow {allowedTargets = 1;};
		class life_fnc_seizePlayerWeaponAction {allowedTargets = 1;};
		class life_fnc_copLights {allowedTargets = 1;};
		class life_fnc_ticketPrompt {allowedTargets = 1;};
		class life_fnc_ticketPaid {allowedTargets = 1;};
		class life_fnc_ausweis {allowedTargets = 1;};
		class life_fnc_simDisable {allowedTargets = 1;};
		class life_fnc_lockVehicle {allowedTargets = 1;};
		class life_fnc_copSiren {allowedTargets = 1;};
		class life_fnc_copSiren2 {allowedTargets = 1;};
		class life_fnc_medicSiren {allowedTargets = 1;};
		class life_fnc_medicSiren2 {allowedTargets = 1;};
		class life_fnc_snow {allowedTargets = 1;};
		class life_fnc_flashbang {allowedTargets = 1;};
		class life_fnc_giveDiff {allowedTargets = 1;};
		class life_fnc_moneytransfer {allowedTargets = 1;};
		class life_fnc_gangInvite {allowedTargets = 1;};
		class life_fnc_lightHouse {allowedTargets = 1;};
		class life_fnc_addaction {allowedTargets = 1;};
		class life_fnc_demoChargeTimer {allowedTargets = 1;};
		class life_fnc_zustand {allowedTargets = 1;};
		class life_fnc_medicLights {allowedTargets = 1;};
		class life_fnc_exptoall {allowedTargets = 1;};
		class life_fnc_medicRequest {allowedTargets = 1;};
		class life_fnc_copMedicRequest {allowedTargets = 1;};
		class life_fnc_corpse {allowedTargets = 1;};
		class life_fnc_revived {allowedTargets = 1;};
		class life_fnc_MuellDeponieSet {allowedTargets = 1;};
		class life_fnc_dialCall {allowedTargets = 1;};
		class life_fnc_setChannel {allowedTargets = 1;};
		class life_fnc_setVar {allowedTargets = 1;};
		class life_fnc_receiveItem {allowedTargets = 1;};
		class life_fnc_receiveMoney {allowedTargets = 1;};
		class life_fnc_phone {allowedTargets = 1;};
		class life_fnc_callAction {allowedTargets = 1;};
		class life_fnc_vehicleEmpd {allowedTargets = 1;};
		class life_fnc_vehicleWarned {allowedTargets = 1;};
		class life_fnc_soundDevice {allowedTargets = 1;};
		class life_fnc_earthquake {allowedTargets = 1;};
		class life_fnc_admininfo {allowedTargets = 1;};
		class life_fnc_massteleportaction {allowedTargets = 1;};
		class life_fnc_fireworks {allowedTargets = 1;};
		class life_fnc_ahwEinsatz {allowedTargets = 1;};
		class life_fnc_endsnow {allowedTargets = 1;};
		class life_fnc_licenseTransfer {allowedTargets = 1;};
		class life_fnc_teargas {allowedTargets = 1;};
		class life_fnc_netSetVar {allowedTargets = 1;};
		class life_fnc_CAH_reciever {allowedTargets = 1;};
		class life_fnc_gangCreated {allowedTargets = 1;};
		class life_fnc_gangDisbanded {allowedTargets = 1;};
		class life_fnc_jailMe {allowedTargets = 1;};
		class life_fnc_impoundMenu {allowedTargets = 1;};
		class life_fnc_robShops2 {allowedTargets = 1;};
		class life_fnc_shopState {allowedTargets = 1;};
		class life_fnc_garageRefund {allowedTargets = 1;};
		class life_fnc_vehicleAnimate {allowedTargets = 1;};
		class life_fnc_flugzeug {allowedTargets = 1;};
		class life_fnc_addVehicle2Chain {allowedTargets = 1;};
		class life_fnc_erollator {allowedTargets = 1;};
		class life_fnc_spikeStripEffect {allowedTargets = 1;};
		class life_fnc_bountyReceive {allowedTargets = 1;};
		class life_fnc_wantedList {allowedTargets = 1;};
		class life_fnc_removeLicenses {allowedTargets = 1;};
		class life_fnc_einsatzzentrale {allowedTargets = 1;};
		class life_fnc_volleyball {allowedTargets = 1;};

		class SOCK_fnc_launcherVersion {allowedTargets = 1;};
		class SOCK_fnc_getnumber {allowedTargets = 1;};
		class SOCK_fnc_dataQuery {allowedTargets = 1;};
		class SOCK_fnc_protocol {allowedTargets = 1;};
		class SOCK_fnc_requestReceived {allowedTargets = 1;};
		class SOCK_fnc_insertPlayerInfo {allowedTargets = 1;};
		class SOCK_fnc_getrealdate {allowedTargets = 1;};
		
		class SOA_fnc_player_query {allowedTargets = 1;};
		class SOA_fnc_clientWireTransfer {allowedTargets = 1;};
		class SOA_fnc_clientGangKick {allowedTargets = 1;};
		class SOA_fnc_clientGetKey {allowedTargets = 1;};
		class SOA_fnc_clientMessage {allowedTargets = 1;};

		class HClient_fnc_SAH_Transaction {allowedTargets = 1;};
		class HClient_fnc_SAH_reciever {allowedTargets = 1;};
		
		//Server
		class crypto_fnc_init {allowedTargets = 2;};
		class crypto_fnc_encrypt {allowedTargets = 2;};
		class DB_fnc_queryRequest {allowedTargets = 2;};
		class DB_fnc_getnumber {allowedTargets = 2;};
		class DB_fnc_version {allowedTargets = 2;};
		class DB_fnc_protocol {allowedTargets = 2;};
		class DB_fnc_kennzeichen {allowedTargets = 2;};
		class DB_fnc_insertRequest {allowedTargets = 2;};
		class DB_fnc_updatePartial {allowedTargets = 2;};
		class DB_fnc_updateRequest {allowedTargets = 2;};
		class SOA_fnc_vehicleStore {allowedTargets = 2;};
		class SOA_fnc_wantedBounty {allowedTargets = 2;};
		class SOA_fnc_wantedAdd {allowedTargets = 2;};
		class SOA_fnc_keyManagement {allowedTargets = 2;};
		class SOA_fnc_setObjVar {allowedTargets = 2;};
		class SOA_fnc_vehicleCreate {allowedTargets = 2;};
		class SOA_fnc_robShops {allowedTargets = 2;};
		class SOA_fnc_shopState {allowedTargets = 2;};
		class SOA_fnc_handleMessages {allowedTargets = 2;};
		class SOA_fnc_getID {allowedTargets = 2;};
		class SOA_fnc_SAH_carSell {allowedTargets = 2;};
		class SOA_fnc_jailSys {allowedTargets = 2;};
		class SOA_fnc_wantedRemove {allowedTargets = 2;};
		class SOA_fnc_cleanupRequest {allowedTargets = 2;};
		class SOA_fnc_updateHouseContainers {allowedTargets = 2;};
		class SOA_fnc_insertGang {allowedTargets = 2;};
		class SOA_fnc_removeGang {allowedTargets = 2;};
		class SOA_fnc_updateGang {allowedTargets = 2;};
		class SOA_fnc_clientGangLeader {allowedTargets = 2;};
		class SOA_fnc_addHouse {allowedTargets = 2;};
		class SOA_fnc_updateHouseTrunk {allowedTargets = 2;};
		class SOA_fnc_sellHouse {allowedTargets = 2;};
		class SOA_fnc_managesc {allowedTargets = 2;};
		class SOA_fnc_spikeStrip {allowedTargets = 2;};	
		class SOA_fnc_wantedPardon {allowedTargets = 2;};	
		class SOA_fnc_cleanupMessages {allowedTargets = 2;};	
		class SOA_fnc_msgRequest {allowedTargets = 2;};	
		class SOA_fnc_wantedFetch {allowedTargets = 2;};	
		class SOA_fnc_vehicleRepaint {allowedTargets = 2;};	
		class SOA_fnc_chopShopSell {allowedTargets = 2;};	
		class SOA_fnc_vehicleDelete {allowedTargets = 2;};	
		class SOA_fnc_spawnVehicle {allowedTargets = 2;};
		class SOA_fnc_getVehicles {allowedTargets = 2;};
		class SOA_fnc_startHC {allowedTargets = 2;};
		class SOA_fnc_getProfileNamespace {allowedTargets = 2;};
		class SOA_fnc_grosseinsatz {allowedTargets = 2;};
		class SOA_fnc_eventcodes {allowedTargets = 2;};
		class SOA_fnc_ahw {allowedTargets = 2;};
	};
	
	class Commands
	{
		mode = 1;
		jip = 1;
		
		//All
		class call {allowedTargets = 0;};
		class say3D {allowedTargets = 0;};
		class playsound {allowedTargets = 0;};
		class switchmove {allowedTargets = 0;};
		class playmove {allowedTargets = 0;};
		class skiptime {allowedTargets = 0;};
		class setovercast {allowedTargets = 0;};
		class setrain {allowedTargets = 0;};
		class setfog {allowedTargets = 0;};
		class settimemultiplier {allowedTargets = 0;};
		class lock {allowedTargets = 0;};
		class hint {allowedTargets = 0;};
		class moveInCargo {allowedTargets = 0;};
		class showHUD {allowedTargets = 0;};
		class setCollisionLight {allowedTargets = 0;};
		class addEventHandler {allowedTargets = 1;};
	};
};