private["_handle"];
_handle = [] spawn life_fnc_stripDownPlayer;
waitUntil {scriptDone _handle};
player forceAddUniform "U_C_WorkerCoveralls";
player addBackpack "B_Kitbag_cbr";
player addItem "Medikit";
player addItem "Toolkit";
player addItem "Toolkit";
player addItem "FirstAidKit";
player addItem "FirstAidKit";
player addItem "ItemMap";
player assignItem "ItemMap";
player addItem "ItemCompass";
player assignItem "ItemCompass";
player addItem "ItemWatch";
player assignItem "ItemWatch";
player addItem "ItemRadio"; 
player assignItem "ItemRadio";
[true,"defib",1] call life_fnc_handleInv;
[true,"painkillers",2] call life_fnc_handleInv;
[true,"bloodbag",2] call life_fnc_handleInv;
[] call life_fnc_saveGear;