/*
Script File Author: Repentz
Script File Mod: Life Server
Script File: RPP_Config_Vehicles.sqf

Description:
Configs for Vehicles
*/
RPP_Vehicle_Config =
[
	//class to finde,class name, text,buy price,sell price,weight,skill,type,License

	//Vehicles
	["RPP_Offroad","C_Offroad_01_F","Offroad",4300,2550,85,0,"Vehicle","Driver License"],
	["RPP_QuadBike","C_Quadbike_01_F","Quadbike",700,300,30,0,"Vehicle","Driver License"],
	["RPP_HatchBack","C_Hatchback_01_F","Hatchback",2000,933,60,0,"Vehicle","Driver License"],

	["red_genesis_16_black","red_genesis_16_black","Test",38000,28000,45,5,"Vehicle","Driver License"],
	["RPP_BMW_M5_Black","RPP_BMW_M5_Black","BMW M5 2012 (Black)",38000,28000,45,5,"Vehicle","Driver License"],
	["RPP_BMW_M5_Red","RPP_BMW_M5_Red","BMW M5 2012 (Red)",38000,28000,45,5,"Vehicle","Driver License"],
	["RPP_BMW_M5_blue","RPP_BMW_M5_blue","BMW M5 2012 (Blue)",38000,28000,45,5,"Vehicle","Driver License"],
	["RPP_BMW_M5_Green","RPP_BMW_M5_Green","BMW M5 2012 (Green)",38000,28000,45,5,"Vehicle","Driver License"],

	["RPP_LamboAWhite","RPP_LamborghiniAventador12_White","Lamborghini Aventador (White)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboABlack","RPP_LamborghiniAventador12_Black","Lamborghini Aventador (Black)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboARed","RPP_LamborghiniAventador12_Red","Lamborghini Aventador (Red)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboABlue","RPP_LamborghiniAventador12_blue","Lamborghini Aventador (Blue)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboAGrey","RPP_LamborghiniAventador12_Grey","Lamborghini Aventador (Grey)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboALightBlue","RPP_LamborghiniAventador12_LighteBlue","Lamborghini Aventador (LightBlue)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboAOrange","RPP_LamborghiniAventador12_Orange","Lamborghini Aventador (Orange)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboAPink","RPP_LamborghiniAventador12_Pink","Lamborghini Aventador (Pink)",240000,180000,55,5,"Vehicle","Driver License"],
	["RPP_LamboAYellow","RPP_LamborghiniAventador12_Yellow","Lamborghini Aventador (Yellow)",240000,180000,55,5,"Vehicle","Driver License"],

	["RPP_RPP_DodgeCharger15_White","RPP_DodgeCharger15_White","Dodge Chargher 2015 (White)",27000,22000,90,5,"Vehicle","Driver License"],
	["RPP_RPP_DodgeCharger15_Black","RPP_DodgeCharger15_Black","Dodge Chargher 2015 (Black)",27000,22000,90,5,"Vehicle","Driver License"],
	["RPP_RPP_DodgeCharger15_Red","RPP_DodgeCharger15_Red","Dodge Chargher 2015 (Red)",27000,22000,90,5,"Vehicle","Driver License"],
	["RPP_RPP_DodgeCharger15_blue","RPP_DodgeCharger15_blue","Dodge Chargher 2015 (blue)",27000,22000,90,5,"Vehicle","Driver License"],
	["RPP_RPP_DodgeCharger15_Green","RPP_DodgeCharger15_Green","Dodge Chargher 2015 (Green)",27000,22000,90,5,"Vehicle","Driver License"],

	["RPP_RPP_CAD_Escalade_12_White","RPP_CAD_Escalade_12_White","Cadillac Escalade 2012 (White)",40000,20000,135,5,"Vehicle","Driver License"],
	["RPP_RPP_CAD_Escalade_12_Black","RPP_CAD_Escalade_12_Black","Cadillac Escalade 2012 (Black)",40000,20000,135,5,"Vehicle","Driver License"],
	["RPP_RPP_CAD_Escalade_12_Red","RPP_CAD_Escalade_12_Red","Cadillac Escalade 2012 (Red)",40000,20000,135,5,"Vehicle","Driver License"],
	["RPP_RPP_CAD_Escalade_12_Blue","RPP_CAD_Escalade_12_Blue","Cadillac Escalade 2012 (Blue)",40000,20000,135,5,"Vehicle","Driver License"],
	["RPP_RPP_CAD_Escalade_12_Yellow","RPP_CAD_Escalade_12_Yellow","Cadillac Escalade 2012 (Yellow)",40000,20000,135,5,"Vehicle","Driver License"],
	["RPP_RPP_CAD_Escalade_12_Green","RPP_CAD_Escalade_12_Green","Cadillac Escalade 2012 (Green)",40000,20000,135,5,"Vehicle","Driver License"],
	["RPP_RPP_CAD_Escalade_12_LightBlue","RPP_CAD_Escalade_12_LightBlue","Cadillac Escalade 2012 (LightBlue)",40000,20000,135,5,"Vehicle","Driver License"],

	["RPP_DodgeChargerSRT8_12_White","RPP_DodgeChargerSRT8_12_White","Dodge Charger SRT8 2012 (White)",21000,17000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Black","RPP_DodgeChargerSRT8_12_Black","Dodge Charger SRT8 2012 (Black)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Red","RPP_DodgeChargerSRT8_12_Red","Dodge Charger SRT8 2012 (Red)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_blue","RPP_DodgeChargerSRT8_12_blue","Dodge Charger SRT8 2012 (Blue)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Green","RPP_DodgeChargerSRT8_12_Green","Dodge Charger SRT8 2012 (Green)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Yellow","RPP_DodgeChargerSRT8_12_Yellow","Dodge Charger SRT8 2012 (Yellow)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_LightBlue","RPP_DodgeChargerSRT8_12_LightBlue","Dodge Charger SRT8 2012 (LightBlue)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Pink","RPP_DodgeChargerSRT8_12_Pink","Dodge Charger SRT8 2012 (Pink)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Orange","RPP_DodgeChargerSRT8_12_Orange","Dodge Charger SRT8 2012 (Orange)",21000,20000,90,3,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Police","RPP_DodgeChargerSRT8_12_Police","Dodge Charger SRT8 2012 (Patrol)",35000,25000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_undercover_Black","RPP_DodgeChargerSRT8_12_undercover_Black","Dodge Charger SRT8 2012 (Undercover Black)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Undercover_White","RPP_DodgeChargerSRT8_12_Undercover_White","Dodge Charger SRT8 2012 (Undercover White)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Undercover_Red","RPP_DodgeChargerSRT8_12_Undercover_Red","Dodge Charger SRT8 2012 (Undercover Red)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Undercover_Green","RPP_DodgeChargerSRT8_12_Undercover_Green","Dodge Charger SRT8 2012 (Undercover Green)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Undercover_LightBlue","RPP_DodgeChargerSRT8_12_Undercover_LightBlue","Dodge Charger SRT8 2012 (Undercover LightBlue)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Undercover_Orange","RPP_DodgeChargerSRT8_12_Undercover_Orange","Dodge Charger SRT8 2012 (Undercover Orange)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_Undercover_Yellow","RPP_DodgeChargerSRT8_12_Undercover_Yellow","Dodge Charger SRT8 2012 (Undercover Yellow)",45000,30000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeChargerSRT8_12_EMT","RPP_DodgeChargerSRT8_12_EMT","Dodge Charger SRT8 2012 (EMT)",6500,200,90,0,"Vehicle","Driver License"],

	["RPP_DodgeCharger15_Police","RPP_DodgeCharger15_Police","Dodge Charger 2015 (Patrol)",3000,1500,90,0,"Vehicle","Driver License"],
	["RPP_DodgeCharger15_EMT","RPP_DodgeCharger15_EMT","Dodge Charger 2015 (EMT)",3000,1500,90,0,"Vehicle","Driver License"],
	["RPP_DodgeCharger15_PoliceUndercover_BASE","RPP_DodgeCharger15_PoliceUndercover_BASE","Dodge Charger 2015 (UnderCover Black)",30000,20000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeCharger15_PoliceUndercover_White","RPP_DodgeCharger15_PoliceUndercover_White","Dodge Charger 2015 (UnderCover White)",30000,20000,90,0,"Vehicle","Driver License"],
	["RPP_DodgeCharger15_PoliceUndercover_Red","RPP_DodgeCharger15_PoliceUndercover_Red","Dodge Charger 2015 (UnderCover Red)",30000,20000,90,0,"Vehicle","Driver License"],

	["RPP_Skyline_Mercedes_C63_01_F","Skyline_Mercedes_C63_01_F","Mercedes-Benz C63 AMG (Spoiler)",35000,31000,90,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_C63_02_F","Skyline_Mercedes_C63_02_F","Mercedes-Benz C63 AMG",32000,30000,90,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_02_F","Skyline_Mercedes_300_SEL_02_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_03_F","Skyline_Mercedes_300_SEL_03_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_04_F","Skyline_Mercedes_300_SEL_04_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_05_F","Skyline_Mercedes_300_SEL_05_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_06_F","Skyline_Mercedes_300_SEL_06_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_07_F","Skyline_Mercedes_300_SEL_07_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_08_F","Skyline_Mercedes_300_SEL_08_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_09_F","Skyline_Mercedes_300_SEL_09_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_10_F","Skyline_Mercedes_300_SEL_10_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],
	["RPP_Skyline_Mercedes_300_SEL_11_F","Skyline_Mercedes_300_SEL_11_F","Mercedes-Benz 300 SEL",12000,10000,85,7,"Vehicle","Driver License"],

	["RPP_shounka_f430_spider_noir","shounka_f430_spider_noir","Ferrari F430 Spider (Black)",61250,32000,90,7,"Vehicle","Driver License"],
	["RPP_shounka_f430_spider_bleufonce","shounka_f430_spider_bleufonce","Ferrari F430 Spider (Dark Blue)",61250,32000,90,7,"Vehicle","Driver License"],
	["RPP_shounka_f430_spider_rouge","shounka_f430_spider_rouge","Ferrari F430 Spider (Red)",61250,32000,90,7,"Vehicle","Driver License"],
	["RPP_shounka_f430_spider_jaune","shounka_f430_spider_jaune","Ferrari F430 Spider (Yellow)",61250,32000,90,7,"Vehicle","Driver License"],
	["RPP_shounka_f430_spider_rose","shounka_f430_spider_rose","Ferrari F430 Spider (Pink)",61250,32000,90,7,"Vehicle","Driver License"],
	["RPP_shounka_f430_spider_grise","shounka_f430_spider_grise","Ferrari F430 Spider (Gray)",61250,32000,90,7,"Vehicle","Driver License"],
	["RPP_shounka_f430_spider_violet","shounka_f430_spider_violet","Ferrari F430 Spider (Purple)",61250,32000,90,7,"Vehicle","Driver License"],

	["RPP_shounka_buggy_noir","shounka_buggy_noir","Buggy (Black)",35000,30000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_buggy_bleufonce","shounka_buggy_bleufonce","Buggy (Black)",35000,30000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_buggy_rouge","shounka_buggy_rouge","Buggy (Red)",35000,30000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_buggy_jaune","shounka_buggy_jaune","Buggy (Yellow)",35000,30000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_buggy_rose","shounka_buggy_rose","Buggy (Pink)",35000,30000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_buggy_grise","shounka_buggy_grise","Buggy (Gray)",35000,30000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_buggy_violet","shounka_buggy_violet","Buggy (Purple)",35000,30000,90,3,"Vehicle","Driver License"],

	["RPP_shounka_porsche911_noir","shounka_porsche911_noir","Porsche 911 (Black)",55000,50000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_porsche911_bleufonce","shounka_porsche911_bleufonce","Porsche 911 (Dark Blue)",55000,50000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_porsche911_rouge","shounka_porsche911_rouge","Porsche 911 (Red)",55000,50000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_porsche911_jaune","shounka_porsche911_jaune","Porsche 911 (Yellow)",55000,50000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_porsche911_rose","shounka_porsche911_rose","Porsche 911 (Pink)",55000,50000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_porsche911_grise","shounka_porsche911_grise","Porsche 911 (Gray)",55000,50000,90,3,"Vehicle","Driver License"],
	["RPP_shounka_porsche911_violet","shounka_porsche911_violet","Porsche 911 (Purple)",55000,50000,90,3,"Vehicle","Driver License"],

	["RPP_Mrshounka_r5_noir","Mrshounka_r5_noir","Renault R5 (Black)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_Mrshounka_r5_bleufonce","Mrshounka_r5_bleufonce","Renault R5 (Dark Blue)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_Mrshounka_r5_rouge","Mrshounka_r5_rouge","Renault R5 (Red)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_Mrshounka_r5_jaune","Mrshounka_r5_jaune","Renault R5 (Yellow)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_Mrshounka_r5_rose","Mrshounka_r5_rose","Renault R5 (Pink)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_MrShounka_r5_grise","MrShounka_r5_grise","Renault R5 (Gray)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_Mrshounka_r5_violet","Mrshounka_r5_violet","Renault R5 (Purple)",3000,2000,60,0,"Vehicle","Driver License"],
	["RPP_Mrshounka_r5_orange","Mrshounka_r5_orange","Renault R5 (Orange)",3000,2000,60,0,"Vehicle","Driver License"],

	["RPP_shounka_a3_cliors_civ_noir","shounka_a3_cliors_civ_noir","Clio RS (Black)",7000,5000,60,0,"Vehicle","Driver License"],
	["RPP_shounka_a3_cliors_civ_bleufonce","shounka_a3_cliors_civ_bleufonce","Clio RS (Dark Blue)",7000,5000,60,0,"Vehicle","Driver License"],
	["RPP_shounka_a3_cliors_civ_rouge","shounka_a3_cliors_civ_rouge","Clio RS (Red)",7000,5000,60,0,"Vehicle","Driver License"],
	["RPP_shounka_a3_cliors_civ_jaune","shounka_a3_cliors_civ_jaune","Clio RS (Yellow)",7000,5000,60,0,"Vehicle","Driver License"],
	["RPP_shounka_a3_cliors_civ_grise","shounka_a3_cliors_civ_grise","Clio RS (Gray)",7000,5000,60,0,"Vehicle","Driver License"],
	["RPP_shounka_a3_cliors_civ_violet","shounka_a3_cliors_civ_violet","Clio RS (Purple)",7000,5000,60,0,"Vehicle","Driver License"],

	["RPP_Mrshounka_a3_308_civ_noir","Mrshounka_a3_308_civ_noir","Peugeot 308 (Black)",2200,1000,60,1,"Vehicle","Driver License"],
	["RPP_Mrshounka_a3_308_civ_bleufonce","Mrshounka_a3_308_civ_bleufonce","Peugeot 308 (Dark Blue)",2200,1000,60,1,"Vehicle","Driver License"],
	["RPP_Mrshounka_a3_308_civ_rouge","Mrshounka_a3_308_civ_rouge","Peugeot 308 (Red)",2200,1000,60,1,"Vehicle","Driver License"],
	["RPP_Mrshounka_a3_308_civ_jaune","Mrshounka_a3_308_civ_jaune","Peugeot 308 (Yellow)",2200,1000,60,1,"Vehicle","Driver License"],
	["RPP_Mrshounka_a3_308_civ_rose","Mrshounka_a3_308_civ_rose","Peugeot 308 (Pink)",2200,1000,60,1,"Vehicle","Driver License"],
	["RPP_Mrshounka_a3_308_civ_violet","Mrshounka_a3_308_civ_violet","Peugeot 308 (Purple)",2200,1000,60,1,"Vehicle","Driver License"],

	["RPP_Mrshounka_mercedes_190_p_noir","Mrshounka_mercedes_190_p_noir","Mercedes 190 (Black)",5000,3000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_mercedes_190_p_bleufonce","Mrshounka_mercedes_190_p_bleufonce","Mercedes 190 (Dark Blue)",5000,3000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_mercedes_190_p_rouge","Mrshounka_mercedes_190_p_rouge","Mercedes 190 (Red)",5000,3000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_mercedes_190_p_jaune","Mrshounka_mercedes_190_p_jaune","Mercedes 190 (Yellow)",5000,3000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_mercedes_190_p_rose","Mrshounka_mercedes_190_p_rose","Mercedes 190 (Pink)",5000,3000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_mercedes_190_p_grise","Mrshounka_mercedes_190_p_grise","Mercedes 190 (Gray)",5000,3000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_mercedes_190_p_violet","Mrshounka_mercedes_190_p_violet","Mercedes 190 (Purple)",5000,3000,60,3,"Vehicle","Driver License"],

	["RPP_Mrshounka_lykan_c_noir","Mrshounka_lykan_c_noir","Lykan HyperSport (Black)",1800000,1600000,60,15,"Vehicle","Driver License"],
	["RPP_Mrshounka_lykan_c_bleufonce","Mrshounka_lykan_c_bleufonce","Lykan HyperSport (Dark Blue)",1800000,1600000,60,15,"Vehicle","Driver License"],
	["RPP_Mrshounka_lykan_c_rouge","Mrshounka_lykan_c_rouge","Lykan HyperSport (Red)",1800000,1600000,60,15,"Vehicle","Driver License"],
	["RPP_Mrshounka_lykan_c_jaune","Mrshounka_lykan_c_jaune","Lykan HyperSport (Yellow)",1800000,1600000,60,15,"Vehicle","Driver License"],
	["RPP_Mrshounka_lykan_c_rose","Mrshounka_lykan_c_rose","Lykan HyperSport (Pink)",1800000,1600000,60,15,"Vehicle","Driver License"],
	["RPP_Mrshounka_lykan_c_grise","Mrshounka_lykan_c_grise","Lykan HyperSport (Gray)",1800000,1600000,60,15,"Vehicle","Driver License"],
	["RPP_Mrshounka_lykan_c_violet","Mrshounka_lykan_c_violet","Lykan HyperSport (Purple)",1800000,1600000,60,15,"Vehicle","Driver License"],

	["RPP_shounka_avalanche_noir","shounka_avalanche_noir","Chevrolet Avalanche (Black)",85000,6000,200,3,"Vehicle","Driver License"],
	["RPP_shounka_avalanche_bleufonce","shounka_avalanche_bleufonce","Chevrolet Avalanche (Dark Blue)",85000,6000,200,3,"Vehicle","Driver License"],
	["RPP_shounka_avalanche_rouge","shounka_avalanche_rouge","Chevrolet Avalanche (Red)",85000,6000,200,3,"Vehicle","Driver License"],
	["RPP_shounka_avalanche_jaune","shounka_avalanche_jaune","Chevrolet Avalanche (Yellow)",85000,6000,200,3,"Vehicle","Driver License"],
	["RPP_shounka_avalanche_rose","shounka_avalanche_rose","Chevrolet Avalanche (Pink)",85000,6000,200,3,"Vehicle","Driver License"],
	["RPP_shounka_avalanche_grise","shounka_avalanche_grise","Chevrolet Avalanche (Gray)",85000,6000,200,3,"Vehicle","Driver License"],
	["RPP_shounka_avalanche_violet","shounka_avalanche_violet","Chevrolet Avalanche (Purple)",85000,6000,200,3,"Vehicle","Driver License"],

	["RPP_Mrshounka_corbillard_c_noir","Mrshounka_corbillard_c_noir","Corbillard (Black)",34000,25000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_corbillard_c_bleufonce","Mrshounka_corbillard_c_bleufonce","Corbillard (Dark Blue)",34000,25000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_corbillard_c_rouge","Mrshounka_corbillard_c_rouge","Corbillard (Red)",34000,25000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_corbillard_c_jaune","Mrshounka_corbillard_c_jaune","Corbillard (Yellow)",34000,25000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_corbillard_c_rose","Mrshounka_corbillard_c_rose","Corbillard (Red)",34000,25000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_corbillard_c_grise","Mrshounka_corbillard_c_grise","Corbillard (Gray)",34000,25000,60,3,"Vehicle","Driver License"],
	["RPP_Mrshounka_corbillard_c_violet","Mrshounka_corbillard_c_violet","Corbillard (Purple)",34000,25000,60,3,"Vehicle","Driver License"],

	["RPP_Mrshounka_yamaha_p_noir","Mrshounka_yamaha_p_noir","Yahama R6 (Black)",7500,4500,35,3,"Vehicle","Bike License"],
	["RPP_Mrshounka_yamaha_p_bleufonce","Mrshounka_yamaha_p_bleufonce","Yahama R6 (Dark Blue)",7500,4500,35,3,"Vehicle","Bike License"],
	["RPP_Mrshounka_yamaha_p_rouge","Mrshounka_yamaha_p_rouge","Yahama R6 (Red)",7500,4500,35,3,"Vehicle","Bike License"],
	["RPP_Mrshounka_yamaha_p_jaune","Mrshounka_yamaha_p_jaune","Yahama R6 (Yellow)",7500,4500,35,3,"Vehicle","Bike License"],
	["RPP_Mrshounka_yamaha_p_rose","Mrshounka_yamaha_p_rose","Yahama R6 (Pink)",7500,4500,35,3,"Vehicle","Bike License"],
	["RPP_Mrshounka_yamaha_p_grise","Mrshounka_yamaha_p_grise","Yahama R6 (Gray)",7500,4500,35,3,"Vehicle","Bike License"],
	["RPP_Mrshounka_yamaha_p_violet","Mrshounka_yamaha_p_violet","Yahama R6 (Purple)",7500,4500,35,3,"Vehicle","Bike License"],


	["RPP_A3L_CVPI_Sheriff_LB","A3L_CVPI_Sheriff_LB","CVPI Marked Patrol (LB)",300,200,80,0,"Vehicle","Driver License"],
	["RPP_A3L_Taurus_Sheriff_Slick","A3L_Taurus_Sheriff_Slick","Taurus Marked Patrol (ST)",300,200,100,0,"Vehicle","Driver License"],
	["RPP_A3L_Charger_Patrol","A3L_Charger_Patrol","Dodge Charger Patrol",300,200,120,0,"Vehicle","Driver License"],
	["RPP_DAR_ExplorerPolice","DAR_ExplorerPolice","Ford PPV Interceptor (LB)",300,200,140,0,"Vehicle","Driver License"],
	["RPP_A3L_ChargerUC_Black_New","A3L_ChargerUC_Black_New","UC Charger (PB)",300,200,120,0,"Vehicle","Driver License"],
	["RPP_A3L_Suburban_UM_Black","A3L_Suburban_UM_Black","UC Suburban (Black)",300,200,140,0,"Vehicle","Driver License"],
	["RPP_A3L_TaurusUC_Black","A3L_TaurusUC_Black","Taurus UC (Black)",300,200,120,0,"Vehicle","Driver License"],
	["RPP_A3L_CVPIUC_Black","A3L_CVPIUC_Black","CV UC (Black)",300,200,140,0,"Vehicle","Driver License"],
	["RPP_A3L_GrandCaravanUC","A3L_GrandCaravanUC","UC Minivan (Black)",300,200,140,0,"Vehicle","Driver License"],
	["RPP_A3L_ChargerUC","A3L_ChargerUC","Charger UC (No Pushbar)",300,200,140,0,"Vehicle","Driver License"],
	["RPP_DAR_TahoeUM","DAR_TahoeUM","UC Tahoe (Black)",300,200,140,0,"Vehicle","Driver License"],
	["RPP_DAR_SwatPolice","DAR_SwatPolice","LenCo BearCat",1000,200,200,3,"Vehicle","Truck License"],
	["RPP_A3L_Taurus_Sheriff_LB","A3L_Taurus_Sheriff_LB","Taurus Marked Patrol (LB)",300,200,120,0,"Vehicle","Driver License"],
	["RPP_A3L_Charger_SERTGrey","A3L_Charger_SERTGrey","SERT Charger (Grey)",300,200,120,0,"Vehicle","Driver License"],
	["RPP_A3L_GrandCaravanUC","A3L_GrandCaravanUC","UC Minivan (Black)",300,200,120,0,"Vehicle","Driver License"],
	["RPP_AM_Escalade_SERT","AM_Escalade_SERT","UC Escalade (Black)",300,200,120,0,"Vehicle","Driver License"],

	//Trucks
	["RPP_C_VAN_01_box_F","C_VAN_01_box_F","Truck Boxer",27000,20000,300,3,"Vehicle","Truck License"],

	["RPP_Skyline_Bus_03_F","Skyline_Bus_03_F","Bus (Green)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_04_F","Skyline_Bus_04_F","Bus (Red)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_05_F","Skyline_Bus_05_F","Bus (Magenta)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_06_F","Skyline_Bus_06_F","Bus (Cyan)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_07_F","Skyline_Bus_07_F","Bus (Yellow)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_08_F","Skyline_Bus_08_F","Bus (Orange)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_09_F","Skyline_Bus_09_F","Bus (Grey)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_10_F","Skyline_Bus_10_F","Bus (Black)",75000,50000,300,5,"Vehicle","Bus License"],
	["RPP_Skyline_Bus_11_F","Skyline_Bus_11_F","Bus (White)",75000,50000,300,5,"Vehicle","Bus License"],

	["RPP_shounka_a3_dafxf_euro6_f","shounka_a3_dafxf_euro6_f","DAFX Euro6 Truck",145000,50000,700,5,"Vehicle","Truck License"],

	["RPP_shounka_ivceco_noir","shounka_ivceco_noir","Iveco Truck (Black)",195000,80000,900,35,"Vehicle","Truck License"],
	["RPP_shounka_ivecco_bleufonce","shounka_ivceco_bleufonce","Iveco Truck (Dark Blue)",195000,80000,900,5,"Vehicle","Truck License"],
	["RPP_shounka_ivceco_rouge","shounka_ivceco_rouge","Iveco Truck (Red)",195000,80000,900,5,"Vehicle","Truck License"],
	["RPP_shounka_ivceco_jaune","shounka_ivceco_jaune","Iveco Truck (Yellow)",195000,80000,900,5,"Vehicle","Truck License"],
	["RPP_shounka_ivceco_rose","shounka_ivceco_rose","Iveco Truck (Pink)",195000,80000,900,5,"Vehicle","Truck License"],
	["RPP_shounka_ivceco_grise","shounka_ivceco_grise","Iveco Truck (Black)",195000,80000,900,5,"Vehicle","Truck License"],
	["RPP_shounka_ivceco_violet","shounka_ivceco_violet","Iveco Truck (Purple)",195000,80000,900,5,"Vehicle","Truck License"],

	["RPP_shounka_monsteur_noir","shounka_monsteur_noir","Monster Truck (Black)",253000,50000,5,5,"Vehicle","Truck License"],
	["RPP_shounka_monsteur_bleufonce","shounka_monsteur_bleufonce","Monster Truck (Dark Blue)",253000,50000,5,5,"Vehicle","Truck License"],
	["RPP_shounka_monsteur_rouge","shounka_monsteur_rouge","Monster Truck (Red)",253000,50000,5,5,"Vehicle","Truck License"],
	["RPP_shounka_monsteur_jaune","shounka_monsteur_jaune","Monster Truck (Yellow)",253000,50000,5,5,"Vehicle","Truck License"],
	["RPP_shounka_monsteur_rose","shounka_monsteur_rose","Monster Truck (Pink)",253000,50000,5,5,"Vehicle","Truck License"],
	["RPP_shounka_monsteur_grise","shounka_monsteur_grise","Monster Truck (Gray)",253000,50000,5,5,"Vehicle","Truck License"],
	["RPP_shounka_monsteur_violet","shounka_monsteur_violet","Monster Truck (Purple)",253000,50000,5,5,"Vehicle","Truck License"],

	//Boat
	["RPP_C_Rubberboat","C_Rubberboat","Rubber Boat",2120,650,75,0,"Vehicle","Boat License"],
	["RPP_C_Boat_Civil_01_F","C_Boat_Civil_01_F","Motorboat",15300,10500,150,3,"Vehicle","Boat License"],
	["RPP_I_G_Boat_Transport_01_F","I_G_Boat_Transport_01_F","Assault Boat",4500,2500,75,1,"Vehicle","Boat License"],
	["RPP_O_Lifeboat","O_Lifeboat","Life Raft (EMT)",250,150,100,0,"Vehicle","Boat License"],
	["RPP_C_Boat_Civil_01_rescue_F","C_Boat_Civil_01_rescue_F","Rescue Motorboat (EMT)",500,200,125,0,"Vehicle","Boat License"],
	["RPP_C_Boat_Civil_01_police_F","C_Boat_Civil_01_police_F","Motorboat (Police)",500,200,125,0,"Vehicle","Boat License"],
	["RPP_B_SDV_01_F","B_SDV_01_F","SDV (Police)",250000,15000,20,5,"Vehicle","Boat License"],
	["RPP_I_SDV_01_F","I_SDV_01_F","SDV",180000,86000,20,50,"Vehicle","Boat License"],

	//Air
	["RPP_dezkit_b206_ls","dezkit_b206_ls","B206 LS",272000,125000,140,0,"Air","Pilot License"],
	["RPP_dezkit_b206_hs","dezkit_b206_hs","B206 HS",272000,125000,140,0,"Air","Pilot License"],
	["RPP_dezkit_b206_fl","dezkit_b206_fl","B206 FL",272000,125000,140,0,"Air","Pilot License"],
	["RPP_dezkit_b206_news","dezkit_b206_news","B206 News",328500,225000,140,0,"Air","Pilot License"],
	["RPP_dezkit_b206_rescue","dezkit_b206_rescue","B206 Rescue Patrol",5000,2000,140,0,"Air","Pilot License"],
	["RPP_dezkit_b206_ems","dezkit_b206_ems","B206 EMS",5000,2000,140,0,"Air","Pilot License"],
	["RPP_dezkit_b206_police","dezkit_b206_police","B206 Patrol",5000,2000,140,0,"Air","Pilot License"],
	["RPP_C_Heli_Light_01_civil_F","C_Heli_Light_01_civil_F","M-900",155000,125000,60,0,"Air","Pilot License"],
	["RPP_O_Heli_Light_02_unarmed_F","O_Heli_Light_02_unarmed_F","PO-30 Orca (Unarmed)",350000,234000,300,5,"Air","Pilot License"],
	["RPP_I_Heli_Transport_02_F","I_Heli_Transport_02_F","CH-49 Mohawk",750000,540000,750,15,"Air","Pilot License"],
	["RPP_C_Heli_light_01_sheriff_F","C_Heli_light_01_sheriff_F","M-900 Police",5000,2000,140,0,"Air","Pilot License"]
	
];
publicVariable "RPP_Vehicle_Config";

RPP_Other_Config =
[
	//RPP_Class, classname, price, sell price, commmand, Cfg, License

	//Backpack
	["RPP_Invisible_Carryall","Invisibe_Carryall",10,0,"addBackpackCargoGlobal","CfgVehicles", ""],
	["RPP_AM_PoliceBelt","AM_PoliceBelt",200,100,"addBackpackCargoGlobal","CfgVehicles",""],


	//Headgear
	["RPP_SO_SHERIFFGRN","SO_SHERIFFGRN",150,130,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_SO_SERTWHITEBLKBK","SO_SERTWHITEBLKBK",150,50,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_TRYK_H_PASGT_OD","TRYK_H_PASGT_OD",150,50,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_Campaign_Hat_Washedout","Campaign_Hat_Washedout",150,50,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_H_HelmetB_light","H_HelmetB_light",150,50,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_EMT_emt_cap","RPP_EMT_emt_cap",5,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_NVGoggles","NVGoggles",5000,4000,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_Kio_Balaclava","TRYK_Kio_Balaclava",630,350,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Bandana_H","TRYK_H_Bandana_H",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Bandana_wig","TRYK_H_Bandana_wig",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Bandana_wig_g","TRYK_H_Bandana_wig_g",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Booniehat_3CD","TRYK_H_Booniehat_3CD",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Booniehat_CC","TRYK_H_Booniehat_CC",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Booniehat_MARPAT_WOOD","TRYK_H_Booniehat_MARPAT_WOOD",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Booniehat_JSDF","TRYK_H_Booniehat_JSDF",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_Booniehat_WOOD","TRYK_H_Booniehat_WOOD",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_LHS_HEL_G","TRYK_H_LHS_HEL_G",630,515,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_ESS_CAP","TRYK_ESS_CAP",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_ESS_CAP_OD","TRYK_ESS_CAP_OD",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_ESS_CAP_tan","TRYK_ESS_CAP_tan",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_R_CAP_BLK","TRYK_R_CAP_BLK",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_R_CAP_TAN","TRYK_R_CAP_TAN",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_R_CAP_OD_US","TRYK_R_CAP_OD_US",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_G_Bandanna_oli","G_Bandanna_oli",50,20,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_TRYK_r_cap_blk_Glasses","TRYK_r_cap_blk_Glasses",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_r_cap_od_Glasses","TRYK_r_cap_od_Glasses",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_r_cap_tan_Glasses","TRYK_r_cap_tan_Glasses",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_wig","TRYK_H_wig",100,70,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_woolhat","TRYK_H_woolhat",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_woolhat_br","TRYK_H_woolhat_br",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_woolhat_cu","TRYK_H_woolhat_cu",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_woolhat_CW","TRYK_H_woolhat_CW",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_woolhat_tan","TRYK_H_woolhat_tan",50,45,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_H_woolhat_WH","TRYK_H_woolhat_WH",50,45,"addItemCargoGlobal","CfgWeapons", ""],


	//Uniform
	["RPP_Fox_Sert","Fox_Sert",200,80,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOSHERIFF","A3L_EC_SOSHERIFF",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOCPT","A3L_EC_SOCPT",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOLT","A3L_EC_SOLT",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOSGT","A3L_EC_SOSGT",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOCPL","A3L_EC_SOCPL",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOOFC","A3L_EC_SOOFC",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_EC_SOCDT","A3L_EC_SOCDT",300,200,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_U_B_Wetsuit","U_B_Wetsuit",500,400,"addItemCargoGlobal","CfgWeapons","Diving License"],
	["RPP_U_B_CombatUniform_mcam","U_B_CombatUniform_mcam",50,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_EMT_emt_uniform","RPP_EMT_emt_uniform",5,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUHsW3nh","TRYK_U_B_PCUHsW3nh",250,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUHsW3","TRYK_U_B_PCUHsW3",250,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUGs_BLK_R","TRYK_U_B_PCUGs_BLK_R",235,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUGs_gry_R","TRYK_U_B_PCUGs_gry_R",235,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUGs_OD_R","TRYK_U_B_PCUGs_OD_R",235,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUGs_BLK","TRYK_U_B_PCUGs_BLK",243,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUGs_gry","TRYK_U_B_PCUGs_gry",243,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_PCUGs_OD","TRYK_U_B_PCUGs_OD",245,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_BLK_OD_Rollup_CombatUniform","TRYK_U_B_BLK_OD_Rollup_CombatUniform",400,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_BK","TRYK_shirts_DENIM_BK",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_BL","TRYK_shirts_DENIM_BL",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_BWH","TRYK_shirts_DENIM_BWH",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_od","TRYK_shirts_DENIM_od",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_R","TRYK_shirts_DENIM_R",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_RED2","TRYK_shirts_DENIM_RED2",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_WH","TRYK_shirts_DENIM_WH",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_WHB","TRYK_shirts_DENIM_WHB",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_ylb","TRYK_shirts_DENIM_ylb",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_od_Sleeve","TRYK_shirts_DENIM_od_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_ylb_Sleeve","TRYK_shirts_DENIM_ylb_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_BK_Sleeve","TRYK_shirts_DENIM_BK_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_BL_Sleeve","TRYK_shirts_DENIM_BL_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_BWH_Sleeve","TRYK_shirts_DENIM_BWH_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_R_Sleeve","TRYK_shirts_DENIM_R_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_RED2_Sleeve","TRYK_shirts_DENIM_BK",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_WH_Sleeve","TRYK_shirts_DENIM_WH_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_shirts_DENIM_WHB_Sleeve","TRYK_shirts_DENIM_WHB_Sleeve",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_denim_hood_3c","TRYK_U_denim_hood_3c",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_denim_hood_blk","TRYK_U_denim_hood_blk",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_denim_hood_mc","TRYK_U_denim_hood_mc",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_denim_hood_nc","TRYK_U_denim_hood_nc",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_denim_jersey_blk","TRYK_U_denim_jersey_blk",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_denim_jersey_blu","TRYK_U_denim_jersey_blu",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_pad_j_blk","TRYK_U_pad_j_blk",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_pad_j","TRYK_U_pad_j",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_BL","TRYK_U_taki_BL",430,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_BLK","TRYK_U_taki_BLK",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_COY","TRYK_U_taki_COY",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_wh","TRYK_U_taki_wh",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_G_BL","TRYK_U_taki_G_BL",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_G_BLK","TRYK_U_taki_G_BLK",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_G_COY","TRYK_U_taki_G_COY",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_taki_G_WH","TRYK_U_taki_G_WH",630,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_SUITS_BLK_F","TRYK_SUITS_BLK_F",1030,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_SUITS_BR_F","TRYK_SUITS_BR_F",1030,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_BLK_T_BG_BK","TRYK_U_B_BLK_T_BG_BK",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_RED_T_BG_BR","TRYK_U_B_RED_T_BG_BR",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_BLK_T_BG_WH","TRYK_U_B_BLK_T_BG_WH",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_BLK_T_BK","TRYK_U_B_BLK_T_BK",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_RED_T_BR","TRYK_U_B_RED_T_BR",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_BLK_T_WH","TRYK_U_B_BLK_T_WH",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_Denim_T_BG_BK","TRYK_U_B_Denim_T_BG_BK",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_Denim_T_BG_WH","TRYK_U_B_Denim_T_BG_WH",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_Denim_T_BK","TRYK_U_B_Denim_T_BK",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_U_B_Denim_T_WH","TRYK_U_B_Denim_T_WH",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_ZARATAKI","TRYK_ZARATAKI",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_ZARATAKI2","TRYK_ZARATAKI2",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_ZARATAKI3","TRYK_ZARATAKI3",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_U_I_Protagonist_VR","U_I_Protagonist_VR",500,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_U_O_Protagonist_VR","U_O_Protagonist_VR",450,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_U_B_Protagonist_VR","U_B_Protagonist_VR",450,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_U_C_WorkerCoveralls","U_C_WorkerCoveralls",450,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_RPP_TRYK_U_B_PCUGs_BLK_R","RPP_TRYK_U_B_PCUGs_BLK_R",600,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_U_C_Poor_1","U_C_Poor_1",450,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_BetaShirt_Polo","RPP_BetaShirt_Polo",50,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_ILoveRPP_Polo","RPP_ILoveRPP_Polo",50,1,"addItemCargoGlobal","CfgWeapons", ""],


	//Vest
	["RPP_A3L_ftovest2","A3L_ftovest2",200,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_TFO_TACVEST_SHERIFF","TFO_TACVEST_SHERIFF",200,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_SERT_FULL_VEST","SERT_FULL_VEST",200,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_sert_uni1","sert_uni1",200,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_A3L_sheriffvest","A3L_sheriffvest",200,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_V_RebreatherB","V_RebreatherB",3500,1000,"addItemCargoGlobal","CfgWeapons","Diving License"],
	["RPP_V_PlateCarrierSpec_rgr","V_PlateCarrierSpec_rgr",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_Sheriff_BA_OD","TRYK_V_Sheriff_BA_OD",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_FBI_BK","TRYK_V_tacv1LC_FBI_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_FBI2_BK","TRYK_V_tacv1LC_FBI2_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1_FBI_BK","TRYK_V_tacv1_FBI_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_MSL_BK","TRYK_V_tacv1LC_MSL_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_MSL_NV","TRYK_V_tacv1LC_MSL_NV",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LMSL_BK","TRYK_V_tacv1LMSL_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LMSL_NV","TRYK_V_tacv1LMSL_NV",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1_P_BK","TRYK_V_tacv1_P_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_P_BK","TRYK_V_tacv1LC_P_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_P2_BK","TRYK_V_tacv1LC_P2_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LP_BK","TRYK_V_tacv1LP_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_SRF_BK","TRYK_V_tacv1LC_SRF_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_SRF2_BK","TRYK_V_tacv1LC_SRF2_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_SRF_OD","TRYK_V_tacv1LC_SRF_OD",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LC_SRF2_OD","TRYK_V_tacv1LC_SRF2_OD",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1LSRF_BK","TRYK_V_tacv1LSRF_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_tacv1_SHERIFF_BK","TRYK_V_tacv1_SHERIFF_BK",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_LBTH_police","LBTH_police",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_LBT_police","LBT_police",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_belt_police","belt_police",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_beltradio_police","beltradio_police",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_V_PlateCarrier_POLICE","TRYK_V_PlateCarrier_POLICE",125,1,"addItemCargoGlobal","CfgWeapons", ""],


	//Items
	["RPP_NVChainBadge","NVChainBadge",4,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_G_bala_wh_NV","TRYK_G_bala_wh_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_balaclava_BLACK_NV","TRYK_balaclava_BLACK_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_balaclava_NV","TRYK_balaclava_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_balaclava_BLACK_EAR_NV","TRYK_balaclava_BLACK_EAR_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_balaclava_EAR_NV","TRYK_balaclava_EAR_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_G_bala_ess_NV","TRYK_G_bala_ess_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_bandana_NV","TRYK_bandana_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_US_ESS_Glasses_Cover","TRYK_US_ESS_Glasses_Cover",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_SPgear_PHC1_NV","TRYK_SPgear_PHC1_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_SPgear_PHC2_NV","TRYK_SPgear_PHC2_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_TRYK_HRPIGEAR_NV","TRYK_HRPIGEAR_NV",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_tf_anprc152_204","tf_anprc152_204",65,1,"addItemCargoGlobal","CfgRadio", ""],
	["RPP_tf_anprc152","tf_anprc152",5,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_Binocular","Binocular",65,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_Release_The_Prisoners_sign","RPP_Release_The_Prisoners_sign",65,1,"addWeaponCargoGlobal","CfgWeapons", ""],
	["RPP_NewsCam","RPP_NewsCam",600,1,"addWeaponCargoGlobal","CfgWeapons", ""],
	["RPP_sign_Base","RPP_sign_Base",65,1,"addWeaponCargoGlobal","CfgWeapons", ""],
	["RPP_RH_x300","RH_x300",65,1,"addWeaponCargoGlobal","CfgWeapons", ""],
	["RPP_acc_flashlight","acc_flashlight",65,1,"addWeaponCargoGlobal","CfgWeapons", ""],
	["RPP_RH_SFM952V","RH_SFM952V",10,5,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_RH_M6X","RH_M6X",10,5,"addWeaponCargoGlobal","CfgWeapons",""],


	//Goggles
	["RPP_G_B_Diving","G_B_Diving",240,100,"addGoggles","CfgGlasses","Diving License"],
	["RPP_G_Aviator","G_Aviator",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Spectacles_Tinted","G_Spectacles_Tinted",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_kio_balaclava_BLK","TRYK_kio_balaclava_BLK",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_kio_balaclava_BLK_ear","TRYK_kio_balaclava_BLK_ear",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_kio_balaclava_ESS","TRYK_kio_balaclava_ESS",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BK","TRYK_Beard_BK",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard","TRYK_Beard",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BW","TRYK_Beard_BW",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_Gr","TRYK_Beard_Gr",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BK2","TRYK_Beard_BK2",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard2","TRYK_Beard2",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BW2","TRYK_Beard_BW2",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_Gr2","TRYK_Beard_Gr2",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BK3","TRYK_Beard_BK3",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard3","TRYK_Beard3",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BW3","TRYK_Beard_BW3",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_Gr3","TRYK_Beard_Gr3",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BK4","TRYK_Beard_BK4",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard4","TRYK_Beard4",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_BW4","TRYK_Beard_BW4",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_TRYK_Beard_Gr4","TRYK_Beard_Gr4",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Bandanna_blk","G_Bandanna_blk",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Balaclava_blk","G_Balaclava_blk",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Bandanna_beast","G_Bandanna_beast",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Spectacles","G_Spectacles",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Sport_Red","G_Sport_Red",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Sport_Blackyellow","G_Sport_Blackyellow",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Sport_BlackWhite","G_Sport_BlackWhite",7,1,"addGoggles","CfgGlasses", ""],
	["RPP_G_Squares_Tinted","G_Squares_Tinted",7,1,"addGoggles","CfgGlasses", ""],


	//Scope
	["RPP_FHQ_optic_ACOG","FHQ_optic_ACOG",200,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_RH_compm4s","RH_compm4s",125,100,"addItemCargoGlobal","CfgWeapons",""],
	["RPP_optic_AMS","optic_AMS",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_Holosight_blk","optic_mas_Holosight_blk",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_Holosight_smg","optic_Holosight_smg",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_KHS_blk","optic_KHS_blk",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_LRPS","optic_LRPS",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_SOS","optic_SOS",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_DMS","optic_mas_DMS",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_Arco_blk","optic_mas_Arco_blk",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_Aco_camo","optic_mas_Aco_camo",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_MRCO_camo","optic_mas_MRCO_camo",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_zeiss","optic_mas_zeiss",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_acog","optic_mas_acog",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_aim","optic_mas_aim",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_PSO","optic_mas_PSO",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_term","optic_mas_term",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_MRD","optic_mas_MRD",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_LRPS","optic_mas_LRPS",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_nspu","optic_mas_nspu",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_kobra","optic_mas_kobra",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_optic_mas_PSO_kv","optic_mas_PSO_kv",125,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_Skyline_scopeVSS_01","Skyline_scopeVSS_01",125,1,"addItemCargoGlobal","CfgWeapons", ""],


	//Supressor - bipod
	["RPP_bipod_01_F_blk","bipod_01_F_blk",35,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_L","muzzle_mas_snds_L",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_LM","muzzle_mas_snds_LM",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_C","muzzle_mas_snds_C",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_MP5SD6","muzzle_mas_snds_MP5SD6",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_M","muzzle_mas_snds_M",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_Mc","muzzle_mas_snds_Mc",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_MP7","muzzle_mas_snds_MP7",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_SM","muzzle_mas_snds_SM",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_SMc","muzzle_mas_snds_SMc",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_SH","muzzle_mas_snds_SH",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_SHc","muzzle_mas_snds_SHc",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_SV","muzzle_mas_snds_SV",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_mas_snds_SVc","muzzle_mas_snds_SVc",75,1,"addItemCargoGlobal","CfgWeapons", ""],
	["RPP_muzzle_snds_M","muzzle_snds_M",75,1,"addItemCargoGlobal","CfgWeapons", ""],


	//Weapons
	["RPP_arifle_mas_l119c","arifle_mas_l119c",200,150,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_srifle_mas_m24","srifle_mas_m24",200,150,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_hlc_rifle_samr2","hlc_rifle_samr2",200,100,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_RH_p226","RH_p226",200,100,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_hlc_rifle_CQBR","hlc_rifle_CQBR",300,100,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_RPP_X26Taser_F","RPP_X26Taser_F",2,1,"addWeaponCargoGlobal","CfgWeapons", ""],
	["RPP_prpl_benelli_pgs_rail","prpl_benelli_pgs_rail",50,20,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_RH_M4A6","RH_M4A6",50,20,"addWeaponCargoGlobal","CfgWeapons",""],
	["RPP_RH_m9","RH_m9",3000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_RH_usp","RH_usp",6000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_RH_uspm","RH_uspm",6200,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_mp5","arifle_mas_mp5",8000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_hk416","arifle_mas_hk416",150000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_m4","arifle_mas_m4",150000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_l119","arifle_mas_l119",350000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_g36c","arifle_mas_g36c",150000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_mk16","arifle_mas_mk16",250000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_srifle_mas_ebr","srifle_mas_ebr",350000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_Skyline_Aug_A1_01_F","Skyline_Aug_A1_01_F",350000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_ajx_browning_hp_F","ajx_browning_hp_F",35000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_srifle_mas_lrr","srifle_mas_lrr",350000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_RH_deagle","RH_deagle",15000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_deagleg","RH_deagleg",15000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_cz75","RH_cz75",700,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_sw659","RH_sw659",650,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_mak","RH_mak",580,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_m1911","RH_m1911",700,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_kimber","RH_kimber",730,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_kimber_nw","RH_kimber_nw",730,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_g19","RH_g19",600,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_g18","RH_g18",600,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_g17","RH_g17",600,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_tt33","RH_tt33",380,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_mk2","RH_mk2",410,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_p226","RH_p226",1000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_vp70","RH_vp70",800,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_mateba","RH_mateba",2000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_python","RH_python",1500,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_mp412","RH_mp412",1500,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_bull","RH_bull",1500,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_ttracker","RH_ttracker",1500,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_fnp45","RH_fnp45",800,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_fn57","RH_fn57",600,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_gsh18","RH_gsh18",500,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_tec9","RH_tec9",5000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_muzi","RH_muzi",5000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_RH_vz61","RH_vz61",5000,1,"addWeaponCargoGlobal","CfgWeapons", "Pistol License"],
	["RPP_arifle_mas_mp40","arifle_mas_mp40",15000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_hgun_mas_mp7_F","hgun_mas_mp7_F",13000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_ak_74m","arifle_mas_ak_74m",17000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_akms","arifle_mas_akms",19000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_bizon","arifle_mas_bizon",10000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_srifle_mas_svd","srifle_mas_svd",150000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_arifle_mas_aks74u","arifle_mas_aks74u",15000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_hgun_mas_uzi_F","hgun_mas_uzi_F",9000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],
	["RPP_hgun_mas_sa61_F","hgun_mas_sa61_F",12000,1,"addWeaponCargoGlobal","CfgWeapons", "Rifle License"],


	//Magazines
	["RPP_hlc_30rnd_556x45_SOST","hlc_30rnd_556x45_SOST",50,20,"addMagazineCargoGlobal","CfgMagazines",""],
	["RPP_5Rnd_mas_762x51_Stanag","5Rnd_mas_762x51_Stanag",50,20,"addMagazineCargoGlobal","CfgMagazines",""],
	["RPP_hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR",50,20,"addMagazineCargoGlobal","CfgMagazines",""],
	["RPP_RH_30Rnd_68x43_FMJ","RH_30Rnd_68x43_FMJ",50,20,"addMagazineCargoGlobal","CfgMagazines",""],
	["RPP_prpl_8Rnd_12Gauge_Pellets","prpl_8Rnd_12Gauge_Pellets",17,12,"addMagazineCargoGlobal","CfgMagazines",""],
	["RPP_X26Taser_cartridge","RPP_X26Taser_cartridge",2,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_15Rnd_9x19_M9","RH_15Rnd_9x19_M9",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_12Rnd_45cal_usp","RH_12Rnd_45cal_usp",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_16Rnd_40cal_usp","RH_16Rnd_40cal_usp",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_30Rnd_mas_9x21_Stanag","30Rnd_mas_9x21_Stanag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_30Rnd_mas_556x45_Stanag","30Rnd_mas_556x45_Stanag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_20Rnd_mas_762x51_Stanag","20Rnd_mas_762x51_Stanag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_10Rnd_mas_338_Stanag","10Rnd_mas_338_Stanag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_30Rnd_556x45_Stanag","30Rnd_556x45_Stanag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_10Rnd_9x39_mag","10Rnd_9x39_mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_20Rnd_9x39_mag","20Rnd_9x39_mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_16Rnd_9x21_Mag","16Rnd_9x21_Mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_7Rnd_50_AE","RH_7Rnd_50_AE",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_16Rnd_9x19_cz","RH_16Rnd_9x19_cz",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_14Rnd_9x19_sw","RH_14Rnd_9x19_sw",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_8Rnd_9x18_Mak","RH_8Rnd_9x18_Mak",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_7Rnd_45cal_m1911","RH_7Rnd_45cal_m1911",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_17Rnd_9x19_g17","RH_17Rnd_9x19_g17",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_33Rnd_9x19_g18","RH_33Rnd_9x19_g18",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_8Rnd_762_tt33","RH_8Rnd_762_tt33",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_10Rnd_22LR_mk2","RH_10Rnd_22LR_mk2",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_15Rnd_9x19_SIG","RH_15Rnd_9x19_SIG",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_18Rnd_9x19_VP","RH_18Rnd_9x19_VP",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_6Rnd_44_Mag","RH_6Rnd_44_Mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_6Rnd_357_Mag","RH_6Rnd_357_Mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_6Rnd_454_Mag","RH_6Rnd_454_Mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_6Rnd_45ACP_Mag","RH_6Rnd_45ACP_Mag",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_15Rnd_45cal_fnp","RH_15Rnd_45cal_fnp",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_20Rnd_57x28_FN","RH_20Rnd_57x28_FN",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_18Rnd_9x19_gsh","RH_18Rnd_9x19_gsh",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_32Rnd_9x19_tec","RH_32Rnd_9x19_tec",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_30Rnd_9x19_UZI","RH_30Rnd_9x19_UZI",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_RH_20Rnd_32cal_vz61","RH_20Rnd_32cal_vz61",25,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_30Rnd_mas_9x21_Stanag","30Rnd_mas_9x21_Stanag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_40Rnd_mas_46x30_Mag","40Rnd_mas_46x30_Mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_30Rnd_mas_545x39_mag","30Rnd_mas_545x39_mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_30Rnd_mas_762x39_mag","30Rnd_mas_762x39_mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_64Rnd_mas_9x18_mag","64Rnd_mas_9x18_mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_10Rnd_mas_762x54_mag","10Rnd_mas_762x54_mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_25Rnd_mas_9x19_Mag","25Rnd_mas_9x19_Mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""],
	["RPP_20Rnd_mas_765x17_Mag","20Rnd_mas_765x17_Mag",100,1,"addMagazineCargoGlobal","CfgMagazines", ""]
];
publicVariable "RPP_Other_Config";
