#include "..\..\script_macros.hpp"
private["_unit","_son"];
_unit = cursorTarget;
_son = "rein";
if(isNull _unit) exitWith {};
if((_unit distance player > 3.5)) exitWith {};
if((_unit getVariable ["missingOrgan",FALSE])) exitWith {};
if((player getVariable ["Escorting",FALSE])) exitWith {};
if((player getVariable ["hasOrgan",FALSE])) exitWith {};
if((player getVariable ["transporting",FALSE])) exitWith {};
if(player == _unit) exitWith {};
if(!isPlayer _unit) exitWith {};
if(ITEM_VALUE("couteau") == 0) exitWith {hint "Vous n'avez pas de couteau !"};
if(life_inv_kidney >= 2) exitWith {hint "Vous pouvez transporter que 2 reins !"};
if(!([true,"kidney",1] call life_fnc_handleInv)) exitWith {hint "Vous n'avez pas assez de place pour transporter d'autres reins !"};
life_action_inUse = true;
player setVariable["hasOrgan",true,true];
player say3D "rein";
//[player, _son, 50] call life_fnc_MP;
player playMove "AinvPknlMstpSnonWnonDnon_medic";
uiSleep 3;
_unit setVariable["missingOrgan",true,true];
life_action_inUse = false;
[[player], "life_fnc_hasOrgan", _unit, false] spawn life_fnc_MP;