 createDialog "airDropMenu"; waitUntil {!(isNull (findDisplay 37400))};  
#define Btn1 37450

#define Btn2 37451

#define Btn3 37452

#define Btn4 37453

#define Btn5 37454

#define Btn6 37455

#define Btn7 37458

#define Btn8 37459

#define Btn9 37460

#define Title 37401
private["_llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv","_hmntvnfvjjkbxdlzlpdfokdxgtgtqfrthpwvoejsqlhwzvvhzjogceejzwydb","_dwsdcagrzpbqhddieqmpgfxstcaapyrjszeuwaekwzwswclxgezjnvftxkgkvzlgmeyb","_cosqdzmfnxrxfmunxsotwtsyxicqkmqlhbyighlwpjqzvlgbsdalcbvzpwihbrxlnvy","_exrqojahenrsrcrpoptbmclmlzqkbnlwddxaidnyaowqyilamzlecployuaepi","_bzvluecdqtuwxrinmolxgptfprxrjsrtwcwztzezhiheigononryrrsdckqdg","_bmzgzqiepcuhqnqljpwylfobmqmwvwqfxcdoevrqsysltwjeyjqzvrdnfxmglvgdzujcvf","_xkvenlzbkotzraktjjzvxjpkjpodowihxsngupqidokhrlsndzanzmgansjco","_kdqmtdnxjioeektwtmkpyrdhmiyeyaglilutkvpeomrgfrwonslhszvzlgzqhq","_ethfiydsqynakiveahqnphsbjbfezeswxqgyvlsgcwglexhyxflopcegqalghdijd9"]; disableSerialization;  _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv = findDisplay 37400; _hmntvnfvjjkbxdlzlpdfokdxgtgtqfrthpwvoejsqlhwzvvhzjogceejzwydb = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn1; _dwsdcagrzpbqhddieqmpgfxstcaapyrjszeuwaekwzwswclxgezjnvftxkgkvzlgmeyb = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn2; _cosqdzmfnxrxfmunxsotwtsyxicqkmqlhbyighlwpjqzvlgbsdalcbvzpwihbrxlnvy = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn3; _exrqojahenrsrcrpoptbmclmlzqkbnlwddxaidnyaowqyilamzlecployuaepi = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn4; _bzvluecdqtuwxrinmolxgptfprxrjsrtwcwztzezhiheigononryrrsdckqdg = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn5; _bmzgzqiepcuhqnqljpwylfobmqmwvwqfxcdoevrqsysltwjeyjqzvrdnfxmglvgdzujcvf = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn6; _xkvenlzbkotzraktjjzvxjpkjpodowihxsngupqidokhrlsndzanzmgansjco = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn7; _kdqmtdnxjioeektwtmkpyrdhmiyeyaglilutkvpeomrgfrwonslhszvzlgzqhq = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn8; _ethfiydsqynakiveahqnphsbjbfezeswxqgyvlsgcwglexhyxflopcegqalghdijd9 = _llseatnwlyqqfwjctsrcckzxnilcglbsfpczcobydmkcgkxspwgyrhqeadwpteruv displayCtrl Btn9;  _bmzgzqiepcuhqnqljpwylfobmqmwvwqfxcdoevrqsysltwjeyjqzvrdnfxmglvgdzujcvf ctrlShow false; _xkvenlzbkotzraktjjzvxjpkjpodowihxsngupqidokhrlsndzanzmgansjco ctrlShow false; _kdqmtdnxjioeektwtmkpyrdhmiyeyaglilutkvpeomrgfrwonslhszvzlgzqhq ctrlShow false; 