/*
	Darkside Life

	Author: Shawn "Huntah" Macgillivray

	Description:
	Returns string name of selected item
*/

params ["_className"];

if([_className,"item"] call DS_fnc_strInStr)then{_className = [_className,"DS_item_",""] call DS_fnc_strReplace};

switch(_className)do {
	case "water": {"Drink this to fully rehydrate yourself"};
	case "donut": {"Taste great, will make you fat. Police love these"};
	case "repairKit": {"Use this on a vehicle to fully repair it"};
	case "refuelKit": {"Use this on a vehicle to partially refuel it"};
	case "lockpick": {"Use this on a vehicle to break its locks and get a copy of its key"};
	case "lighter": {"Use this on a vehicle to set its fuel tank alight and watch it blow up"};
	case "siphonKit": {"Use this on a vehicle to siphon some fuel from it"};
	case "nitro": {"Use this on a vehicle to gain NOS boosts"};
	case "goKart": {"Use this to unpack a Portable Go Kart"};
	case "coffee": {"Drink this to rehydrate yourself"};
	case "pepsi": {"Drink this to rehydrate yourself"};
	case "apple": {"Eat this to keep your hunger pains in check"};
	case "rabbit": {"Eat this to keep your hunger pains in check"};
	case "salema": {"Eat this to keep your hunger pains in check"};
	case "ornate": {"Eat this to keep your hunger pains in check"};
	case "mackerel": {"Eat this to keep your hunger pains in check"};
	case "tuna": {"Eat this to keep your hunger pains in check"};
	case "mullet": {"Eat this to keep your hunger pains in check"};
	case "catshark": {"Eat this to keep your hunger pains in check"};
	case "turtle": {"Eat this to keep your hunger pains in check"};
	case "tbacon": {"Eat this to keep your hunger pains in check"};
	case "peach": {"Eat this to keep your hunger pains in check"};
	case "pie": {"Eat this to keep your hunger pains in check"};
	case "burger": {"Eat this to keep your hunger pains in check"};
	case "chips": {"Eat this to keep your hunger pains in check"};
	case "doritos": {"Eat this to keep your hunger pains in check"};
	case "mediKit": {"Use this to fully heal yourself"};
	case "heroinp": {"Sell this drug at an illegal goods dealer"};
	case "cocainep": {"Sell this drug at an illegal goods dealer"};
	case "weedp": {"Sell this drug at an illegal goods dealer"};
	case "heroinu": {"Process this raw drug at the appropriate gang hideout"};
	case "cocaineu": {"Process this raw drug at the appropriate gang hideout"};
	case "weedu": {"Process this raw drug at the appropriate gang hideout"};
	case "hydro": {"Combine this with Sodium Hydroxide at the Crystal Meth Processor to create Crystal Meth"};
	case "sodium": {"Combine this with Hydrochloric Acid at the Crystal Meth Processor to create Crystal Meth"};
	case "hydroPack": {"Use this to receive some Hydrochloric Acid"};
	case "sodiumPack": {"Use this to receive some Sodium Hydroxide"};
	case "illegalRelicu": {"Clean this at a gang hideout to prepare it for selling"};
	case "illegalRelicp": {"Sell this at an illegal goods dealer"};
	case "meth": {"Sell this at an illegal goods dealer"};
	case "goldBar": {"Trade this for cash at a rebel items trader"};
	case "spyDocs": {"Sell this at a rebel items trader"};
	case "pickAxe": {"Use this by pressing tab at mining fields to collect resources"};
	case "oilu": {"Process this at the oil processor"};
	case "diamondu": {"Process this at the diamond processor"};
	case "copperu": {"Process this at the copper processor"};
	case "rocku": {"Process this at the cement processor"};
	case "saltu": {"Process this at the salt processor"};
	case "ironu": {"Process this at the iron processor"};
	case "sandu": {"Process this at the sand processor"};
	case "woodu": {"Process this at the lumber processor"};
	case "woodp": {"Sell or use this at a factory"};
	case "oilp": {"Sell or use this at a factory"};
	case "diamondp": {"Sell or use this at a factory"};
	case "copperp": {"Sell or use this at a factory"};
	case "rockp": {"Sell or use this at a factory"};
	case "saltp": {"Sell or use this at a factory"};
	case "ironp": {"Sell or use this at a factory"};
	case "sandp": {"Sell or use this at a factory"};
	case "relic": {"Sell or use this at a factory"};
	case "c4": {"Use this to destroy various things such as the Bank Gate, Jail Gate and Power Station"};
	case "defuse": {"Used by police to defuse C4"};
	case "battery": {"Use this to enable usage of the Night Stalker scope"};
	case "cracker": {"Use this to crack the safes at Fort Knox"};
	case "spikeStrip": {"Use this to place a spike strip to blow a vehicles tyres out"};
	case "UAV": {"Use this to place a thermal aerial UAV that can be used to scout for criminals"};
	case "fuelDart": {"Used by the police inside of a fuel dart launcher to drain fuel from a criminal's vehicle"};
	case "vodka": {"Drink this to get drunk and increase your carry weight for 10 minutes"};
	case "bourbon": {"Drink this to get drunk and increase your carry weight for 10 minutes"};
	case "bpVehSecurity": {"Vehicle Security Blueprint (Click 'use' for details)"};
	case "bpVehWeight": {"Vehicle Capacity Blueprint (Click 'use' for details)"};
	case "bpVehFuel": {"Vehicle Fuel Blueprint (Click 'use' for details)"};
	case "bpVehNos": {"Vehicle NOS Blueprint (Click 'use' for details)"};
	case "mattBronze": {"An ingredient used at a factory"};
	case "mattCrystalGlass": {"An ingredient used at a factory"};
	case "mattCircuitBoard": {"An ingredient used at a factory"};
	case "mattSmallBattery": {"An ingredient used at a factory"};
	case "mattCpu": {"An ingredient used at a factory"};
	case "mattSteel": {"An ingredient used at a factory"};
	case "mattTreatedLumber": {"An ingredient used at a factory"};
	case "vehSecurity": {"Use this on a vehicle to improve its security"};
	case "vehWeight": {"Use this on a vehicle to increase its capacity"};
	case "vehFuel": {"Use this on a vehicle to enhance its fuel consumption"};
	case "vehSecurityAdv": {"Use this on a vehicle to improve its security"};
	case "vehWeightAdv": {"Use this on a vehicle to improve its carry weight"};
	case "vehFuelAdv": {"Use this on a vehicle to improve its fuel consumption"};
	case "chute": {"Use this by scrolling while 100m up in the air in an air vehicle"};
	case "fire": {"Place this campfire anywhere to be able to heal at it"};
	case "ziptie": {"Press shift R on a knocked out or surrendered player to restrain them in zipties"};
	case "bpGunLynx": {"Lynx Blueprint (Click 'use' for details)"};
	case "gunLynx": {"Use this to convert it into a Lynx"};
	case "gunLynxAdv": {"Use this to convert it into a LRPS Lynx"};
	case "bpAmmoLynx": {"Lynx Ammo Blueprint (Click 'use' for details)"};
	case "bpAmmoRpg": {"AT RPG Rocket Blueprint (Click 'use' for details)"};
	case "ammoRpg": {"Use this to convert it into a RPG AT Rocket"};
	case "ammoRpgAdv": {"Use this to convert it into 3x RPG AT Rockets"};
	case "ied": {"Improvised Explosive Device"};
	case "buildingBox": {"Building Box"};
	case "vehNos": {"Use this on a vehicle to gain 5 NOS boosts"};
	case "vehNosAdv": {"Use this on a vehicle to gain 10 NOS boosts"};
	case "houseItemUpgrade": {"You must have this item in your inventory when you attempt to upgrade storage beyond its capacity"};
	case "houseWeaponUpgrade": {"You must have this item in your inventory when you attempt to upgrade storage beyond its capacity"};
	case "jail10": {"Use this item to place a ladder"};
	case "safeCrackerAdv": {"Have this item in your inventory while cracking a safe at Fort Knox or the Research Facility to have the time lowered by 5 minutes"};
	case "jailBreak": {"Use this while in jail to be instantly broken out"};
	case "steroids": {"Use this to have your carry weight increased to 500kg for 1 hour"};
	case "noRecoil": {"Use this to have a very steady aim for 10 minutes"};
	case "quickCap": {"Have this item in your inventory while capturing Rebel KOS to capture it much quicker"};
	case "pawnee": {"Use this to spawn in a fully armed rental Pawnee"};
	case "convoy": {"Have this item in your inventory when starting a rebel convoy to disable the server wide alert"};
	case "wheatu": {"Process this at the bakery to make bread to sell"};
	case "wheatp": {"Eat this or sell it at the market for profit"};
	case "vehAmmo": {"Adds ammo to the following vehicles (Hunter, Ifrit, Strider, Armed Offroad, Gorgon)"};
	case "ammoFlash": {"Use this to put 5 Flash Grenades into your inventory"};
	case "ammoTear": {"Use this to put 5 Tear Gas Grenades into your inventory"};
	case "bpVehSUV": {"Special Vehicle Fuel Blueprint (Click 'use' for details)"};
	case "bpGunRpg": {"RPG Launcher Blueprint (Click 'use' for details)"};
	case "gunRpg": {"Use this to convert it into a RPG Launcher"};
	case "bpGun3gl": {"AK12 GL Blueprint (Click 'use' for details)"};
	case "gun3gl": {"Use this to convert it into an AK12 GL"};
	case "bpGunNavid": {"Navid Blueprint (Click 'use' for details)"};
	case "gunNavid": {"Use this to convert it into a Navid"};
	case "gunCyrus": {"Use this to convert it into a Cyrus"};
	case "weaponsAir": {"Adds ammo to the following air vehicles (Pawnee, Orca, Kajman, Blackfoot)"};
	case "weaponsLand": {"Adds ammo to the following land vehicles (Hunter, Ifrit, Strider, Armed Offroad, Gorgon)"};
	case "blackfoot": {"Blackfoot Helicopter"};
	case "bpCyrus": {"Cyrus Weapon Blueprint (Click 'use' for details)"};
	case "bpWeaponsAir": {"Air Vehicle Ammo Blueprint (Click 'use' for details)"};
	case "bpWeaponsLand": {"Land Vehicle Ammo Blueprint (Click 'use' for details)"};
	case "bpBlackfoot": {"Blackfoot Blueprint (Click 'use' for details)"};
	case "armour": {"Provides stun protection to civilians and bullet protection to police"};
	case "packSteel": {"Pack of 200 Steel"};
	case "packBronze": {"Pack of 200 Bronze"};
	case "packGlass": {"Pack of 200 Crystal Glass"};
	case "packCircuitBoard": {"Pack of 30 Circuit Boards"};
	case "packBattery": {"Pack of 30 Small Batteries"};
	case "packCPU": {"Pack of 15 CPU's"};
	case "idChanger": {"Use this to change your ID until you're arrested"};
	case "bones": {"Traded at hospitals for cash by medics"};
	case "goldBarMedium": {"A Medium bag of money traded at rebel dealers"};
	case "goldBarLarge": {"A Large bag of money traded at rebel dealers"};
	case "bpAmmoRpgHE": {"HE RPG Rocket Blueprint (Click 'use' for details)"};
	case "ammoRpgHE": {"Use this to convert it into a RPG HE Rocket"};
	case "ammoRpgHEAdv": {"Use this to convert it into 3x RPG HE Rockets"};
	case "bpGunRpg7": {"RPG7 Launcher Blueprint (Click 'use' for details)"};
	case "bpAirbags": {"Vehicle Airbags Blueprint (Click 'use' for details)"};
	case "bpInsurance": {"Vehicle Insurance Blueprint (Click 'use' for details)"};
	case "bpArmourAdv": {"Advanced Body Armour Blueprint (Click 'use' for details)"};
	case "bpGunSpmg": {"SPMG Blueprint (Click 'use' for details)"};
	case "gunRpg7": {"Use this to convert it into an RPG7"};
	case "airBags": {"Use this on a vehicle to give it 100 air bags"};
	case "insurance": {"Use this on a vehicle to give it one insurance life"};
	case "armourAdv": {"Use this to give yourself 50% stronger body armour"};
	case "gunSpmg": {"Use this to convert it into an SPMG"};
	case "bpAmmoRpg7": {"RPG7 Rocket Blueprint (Click 'use' for details)"};
	case "ammoRpg7": {"Use this to convert it into a RPG7 Rocket"};
	case "ammoRpg7Adv": {"Use this to convert it into a 3x RPG7 Rockets"};
	case "plane": {"Use this to convert it into a armed plane (Use in an area you can take off from)"};
	default {""};
};