/*
	Darkside Life

	Author: Shawn "Huntah" Macgillivray

	Description:
	Returns string name of selected item
*/

params ["_className"];

if([_className,"item"] call DS_fnc_strInStr)then {_className = [_className,"DS_item_",""] call DS_fnc_strReplace};

switch(_className)do {
	case "water": {"Bottled Water"};
	case "donut": {"Frosted Donut"};
	case "repairKit": {"Repair Kit"};
	case "refuelKit": {"Refuel Kit"};
	case "lockpick": {"Lock pick"};
	case "lighter": {"Lighter"};
	case "siphonKit": {"Fuel Siphon Kit"};
	case "nitro": {"Nitrous Oxide"};
	case "goKart": {"Portable Go Kart"};
	case "coffee": {"Hot Coffee"};
	case "pepsi": {"Cold Pepsi"};
	case "apple": {"Apple"};
	case "rabbit": {"Rabbit"};
	case "salema": {"Salema"};
	case "ornate": {"Ornate"};
	case "mackerel": {"Mackerel"};
	case "tuna": {"Tuna"};
	case "mullet": {"Mullet"};
	case "catshark": {"Catshark"};
	case "turtle": {"Turtle"};
	case "tbacon": {"Tactical Bacon"};
	case "peach": {"Peach"};
	case "pie": {"Hot Pie"};
	case "burger": {"Cheese Burger"};
	case "chips": {"Hot Chips"};
	case "doritos": {"Doritos"};
	case "mediKit": {"MediKit"};
	case "heroinp": {"Processed Heroin"};
	case "cocainep": {"Processed Cocaine"};
	case "weedp": {"Processed Weed"};
	case "heroinu": {"Unprocessed Heroin"};
	case "cocaineu": {"Unprocessed Cocaine"};
	case "weedu": {"Unprocessed Weed"};
	case "hydro": {"Hydrochloric Acid"};
	case "sodium": {"Sodium Hydroxide"};
	case "hydroPack": {"Hydrochloric Acid Pack"};
	case "sodiumPack": {"Sodium Hydroxide Pack"};
	case "illegalRelicu": {"Dirty Illegal Relic"};
	case "illegalRelicp": {"Washed Illegal Relic"};
	case "meth": {"Crystal Meth"};
	case "goldBar": {"Money Bag (Small)"};
	case "spyDocs": {"Classified Documents"};
	case "pickAxe": {"Mining Pickaxe"};
	case "oilu": {"Unprocessed Oil"};
	case "diamondu": {"Unprocessed Diamond"};
	case "copperu": {"Unprocessed Copper"};
	case "rocku": {"Unprocessed Rock"};
	case "saltu": {"Unprocessed Salt"};
	case "ironu": {"Unprocessed Iron"};
	case "sandu": {"Unprocessed Sand"};
	case "woodu": {"Unprocessed Lumber"};
	case "woodp": {"Treated Lumber"};
	case "oilp": {"Refined Oil"};
	case "diamondp": {"Cut Diamond"};
	case "copperp": {"Copper Ingot"};
	case "rockp": {"Cement"};
	case "saltp": {"Processed Salt"};
	case "ironp": {"Iron Ingot"};
	case "sandp": {"Glass"};
	case "relic": {"Relic"};
	case "vodka": {"Vodka"};
	case "bourbon": {"Bourbon"};
	case "c4": {"C4 Explosive"};
	case "defuse": {"Defusal Kit"};
	case "battery": {"NightStalker Battery"};
	case "cracker": {"Cracking Device"};
	case "spikeStrip": {"Spike Strip"};
	case "UAV": {"Portable UAV"};
	case "fuelDart": {"Fuel Dart"};
	case "bpVehSecurity": {"Vehicle Security Upgrade Blueprint"};
	case "bpVehWeight": {"Vehicle Capacity Upgrade Blueprint"};
	case "bpVehFuel": {"Vehicle Fuel Upgrade Blueprint"};
	case "mattBronze": {"Treated Bronze"};
	case "mattCrystalGlass": {"Crystal Glass"};
	case "mattCircuitBoard": {"Circuit Board"};
	case "mattSmallBattery": {"Small Battery"};
	case "mattCpu": {"CPU"};
	case "mattSteel": {"Steel"};
	case "mattTreatedLumber": {"Hardened Lumber"};
	case "vehSecurity": {"Vehicle Security Upgrade"};
	case "vehWeight": {"Vehicle Capacity Upgrade"};
	case "vehFuel": {"Vehicle Fuel Upgrade"};
	case "vehSecurityAdv": {"Super Vehicle Security Upgrade"};
	case "vehWeightAdv": {"Super Vehicle Capacity Upgrade"};
	case "vehFuelAdv": {"Super Vehicle Fuel Upgrade"};
	case "vehNos": {"5 Use NOS Kit"};
	case "vehNosAdv": {"10 Use NOS Kit"};
	case "chute": {"Parachute"};
	case "fire": {"Camp Fire"};
	case "ziptie": {"Ziptie"};
	case "bpGunLynx": {"Lynx Blueprint"};
	case "gunLynx": {"Lynx Gun"};
	case "gunLynxAdv": {"LRPS Lynx Gun"};
	case "bpAmmoLynx": {"Lynx Ammo Blueprint"};
	case "ammoLynx": {"Lynx Ammo"};
	case "ammoLynxAdv": {"5 Pack of Lynx Ammo"};
	case "bpAmmoRpg": {"AT RPG Rocket Blueprint"};
	case "ammoRpg": {"RPG AT Rocket"};
	case "ammoRpgAdv": {"3x RPG AT Rocket"};
	case "plane": {"Armed Plane"};
	case "ied": {"I.E.D"};
	case "buildingBox": {"Building Box"};
	case "bodyArmour": {"Body Armour"};
	case "bpVehNos": {"5 NOS Kit Blueprint"};
	case "houseItemUpgrade": {"House Items Storage Upgrade"};
	case "houseWeaponUpgrade": {"House Weapons Storage Upgrade"};
	case "jail10": {"Rebel Ladder"};
	case "safeCrackerAdv": {"Super Safe Cracker"};
	case "jailBreak": {"Jail Breaker"};
	case "steroids": {"Steroids"};
	case "noRecoil": {"Steady Aim"};
	case "quickCap": {"Quick KOS Capper"};
	case "pawnee": {"Fully Armed Pawnee"};
	case "convoy": {"Silent Convoy Starter"};
	case "wheatu": {"Wheat"};
	case "wheatp": {"Bread"};
	case "vehAmmo": {"Vehicle Ammo Upgrade"};
	case "ammoFlash": {"Flash Grenade 5 Pack"};
	case "ammoTear": {"Tear Gas 5 Pack"};
	case "bpVehSUV": {"Bulletproof SUV Blueprint"};
	case "bpGunRpg": {"RPG Launcher Blueprint"};
	case "gunRpg": {"RPG Launcher"};
	case "bpGun3gl": {"AK12 GL Blueprint"};
	case "gun3gl": {"AK12 GL"};
	case "gunNavid": {"Navid Weapon"};
	case "bpGunNavid": {"Navid Blueprint"};
	case "gunCyrus": {"Cyrus Weapon"};
	case "weaponsAir": {"Air Vehicle Ammo Upgrade"};
	case "weaponsLand": {"Land Vehicle Ammo Upgrade"};
	case "blackfoot": {"Blackfoot Helicopter"};
	case "bpCyrus": {"Cyrus Weapon Blueprint"};
	case "bpWeaponsAir": {"Air Vehicle Ammo Blueprint"};
	case "bpWeaponsLand": {"Land Vehicle Ammo Blueprint"};
	case "bpBlackfoot": {"Blackfoot Blueprint"};
	case "packSteel": {"200 Steel"};
	case "packBronze": {"200 Bronze"};
	case "packGlass": {"200 Crystal Glass"};
	case "packCircuitBoard": {"30 Circuit Boards"};
	case "packBattery": {"30 Small Batteries"};
	case "packCPU": {"15 CPU's"};
	case "armour": {"Stun/Body Armour"};
	case "idChanger": {"Fake ID"};
	case "bones": {"Human Remains"};
	case "goldBarMedium": {"Money Bag (Medium)"};
	case "goldBarLarge": {"Money Bag (Large)"};
	case "bpAmmoRpgHE": {"HE RPG Rocket Blueprint"};
	case "ammoRpgHE": {"RPG HE Rocket"};
	case "ammoRpgHEAdv": {"3x RPG HE Rocket"};
	case "bpGunRpg7": {"RPG7 Blueprint"};
	case "bpAirbags": {"Vehicle Airbags Blueprint"};
	case "bpInsurance": {"Vehicle Insurance Blueprint"};
	case "bpArmourAdv": {"Advanced Body Armour Blueprint"};
	case "bpGunSpmg": {"SPMG Blueprint"};
	case "gunRpg7": {"RPG7"};
	case "airBags": {"Vehicle Airbags"};
	case "insurance": {"Vehicle Insurance"};
	case "armourAdv": {"Advanced Body Armour"};
	case "gunSpmg": {"SPMG"};
	case "bpAmmoRpg7": {"RPG7 Rocket Blueprint"};
	case "ammoRpg7": {"RPG7 Rocket"};
	case "ammoRpg7Adv": {"RPG7 Rocket x3"};
	case "DSL_car": {"Car License"};
	case "DSL_truck": {"Truck License"};
	case "DSL_air": {"Pilot License"};
	case "DSL_boat": {"Boating License"};
	case "DSL_weapons": {"Small Firearms License"};
	case "DSL_rebel": {"Rebel Training"};
	case "DSL_rebelAdv": {"Advanced Rebel Training"};
	case "DSL_rebelVeh": {"Rebel Vehicle Training"};
	case "DSL_weaponsAdv": {"Advanced Gun License"};
	case "DSL_oil": {"Oil Processing Training"};
	case "DSL_diamond": {"Diamond Processing Training"};
	case "DSL_copper": {"Copper Processing Training"};
	case "DSL_rock": {"Rock Processing Training"};
	case "DSL_salt": {"Salt Processing Training"};
	case "DSL_iron": {"Iron Processing Training"};
	case "DSL_sand": {"Sand Processing Training"};
	case "DSL_weed": {"Weed Processing Training"};
	case "DSL_heroin": {"Heroin Processing Training"};
	case "DSL_cocaine": {"Cocaine Processing Training"};
	case "DSL_wood": {"Lumber Processing Training"};
	default {""};
};