/*
	Darkside Life

	Author: Shawn "Huntah" Macgillivray

	Description:
	Fills the array and sets up variables for shop items
*/

params ["_shop"];

private _return = [];

if((!DS_spotted)&&((DS_wanted_Stats select 0) > 0))then{[]spawn DS_fnc_recordAdd;};

switch(_shop)do {
	case 666: {_return = ["ATM","atm","Access your bank account"]};
	case 0: {_return = ["Civilian Car Shop","carShop","Buy civilian cars here"]};
	case 1: {_return = ["Civilian Truck Shop","truckShop","Buy civilian trucks here"]};
	case 2: {_return = ["Civilian Air Shop","airShop","Buy civilian air vehicles here"]};
	case 3: {_return = ["Civilian Boat Shop","boatShop","Buy civilian sea vehicles here"]};
	case 4: {_return = ["Civilian Market","market","Buy civilian inventory items here"]};
	case 5: {_return = ["High Tech Store","hitech","Buy your high tech items here"]};
	case 6: {_return = ["Civilian Weapons shop","gun","Buy your legal civilian firearms here"]};
	case 7: {_return = ["Advanced Weapons shop","gunAdv","Buy your legal advanced civilian firearms here"]};
	case 8: {_return = ["Main License shop","license","Purchase most legal licenses at this shop"]};
	case 9: {_return = ["Civilian Clothing Shop","civClothing","Buy your civilian clothing here"]};
	case 10: {_return = ["Civilian Hat Shop","civHats","Buy your civilian hats here"]};
	case 11: {_return = ["Civilian Glasses Shop","civGlasses","Buy your civilian Glasses here"]};
	case 12: {_return = ["Civilian Backpack Shop","civBackpack","Buy your civilian backpacks here"]};
	case 13: {_return = ["Civilian Diving Shop","civDiving","Buy your civilian diving gear here"]};
	case 14: {_return = ["Police Weapons","\a3\ui_f\data\gui\cfg\Ranks\colonel_gs.paa","Police weapons and items are bought here"]};
	case 15: {_return = ["Patrol Officer Weapons","\a3\ui_f\data\gui\cfg\Ranks\corporal_gs.paa","Weapons and items for Patrol Officers are bought here"]};
	case 16: {_return = ["Sergeant Weapons","\a3\ui_f\data\gui\cfg\Ranks\sergeant_gs.paa","Weapons and items for Sergeants are bought here"]};
	case 17: {_return = ["Senior Sergeant Weapons","\a3\ui_f\data\gui\cfg\Ranks\lieutenant_gs.paa","Weapons and items for Senior Sergeants are bought here"]};
	case 18: {_return = ["Lieutenant Weapons","\a3\ui_f\data\gui\cfg\Ranks\captain_gs.paa","Weapons and items for Lieutenants are bought here"]};
	case 19: {_return = ["Superintendent Weapons","\a3\ui_f\data\gui\cfg\Ranks\major_gs.paa","Weapons and items for Superintendents are bought here"]};
	case 20: {_return = ["Deputy Chief Weapons","\a3\ui_f\data\gui\cfg\Ranks\colonel_gs.paa","Weapons and items for Deputy Chiefs are bought here"]};
	case 21: {_return = ["Police Attachments","scope","Attachments for police weapons are bought here"]};
	case 22: {_return = ["Police Items","market","Police inventory items are bought here"]};
	case 23: {_return = ["Police Item Kit","market","Buy your full item kit here"]};
	case 24: {_return = ["Police Clothing","\a3\ui_f\data\gui\cfg\Ranks\major_gs.paa","Buy your police clothing here"]};
	case 25: {_return = ["Patrol Officer Clothing","\a3\ui_f\data\gui\cfg\Ranks\corporal_gs.paa","Buy your low ranking police clothing here"]};
	case 26: {_return = ["Sergeant Clothing","\a3\ui_f\data\gui\cfg\Ranks\sergeant_gs.paa","Buy your mid ranking police clothing here"]};
	case 27: {_return = ["Snr Sergeant Clothing","\a3\ui_f\data\gui\cfg\Ranks\lieutenant_gs.paa","Buy your mid ranking police clothing here"]};
	case 28: {_return = ["Lieutenant Clothing","\a3\ui_f\data\gui\cfg\Ranks\captain_gs.paa","Buy your high ranking police clothing here"]};
	case 29: {_return = ["Super Intendant Clothing","\a3\ui_f\data\gui\cfg\Ranks\major_gs.paa","Buy your high ranking police clothing here"]};
	case 30: {_return = ["Rent-A-Cop Vehicles","carShop","Buy your public officer vehicles here"]};
	case 31: {_return = ["Cadet Vehicles","\a3\ui_f\data\gui\cfg\Ranks\private_gs.paa","Buy your Cadet vehicles here"]};
	case 32: {_return = ["Patrol Officer Vehicles","\a3\ui_f\data\gui\cfg\Ranks\corporal_gs.paa","Buy your patrol Officer vehicles here"]};
	case 33: {_return = ["Sergeant vehicles","\a3\ui_f\data\gui\cfg\Ranks\sergeant_gs.paa","Buy your Sergeant vehicles here"]};
	case 34: {_return = ["Snr Sergeant Vehicles","\a3\ui_f\data\gui\cfg\Ranks\lieutenant_gs.paa","Buy your Senior Sergeant vehicles here"]};
	case 35: {_return = ["Police Vehicles","\a3\ui_f\data\gui\cfg\Ranks\captain_gs.paa","Buy your police vehicles here"]};
	case 36: {_return = ["Police Air Vehicles","airShop","Buy your police air vehicles here"]};
	case 37: {_return = ["Body Armour","armour","Buy your body armour here"]};
	case 38: {_return = ["Process Oil","oilu","Process your oil here"]};
	case 39: {_return = ["Processing Training","license","Purchase your processing training certificates here"]};
	case 40: {_return = ["Process Sand","sandu","Process your sand into glass here"]};
	case 41: {_return = ["Process Salt","saltu","Process your salt here"]};
	case 42: {_return = ["Process Rocks","rocku","Process your rocks into cement here"]};
	case 43: {_return = ["Process Iron","ironu","Process your Iron here"]};
	case 44: {_return = ["Process Diamonds","diamondu","Process your Diamonds here"]};
	case 45: {_return = ["Process Copper","copperu","Process your Copper here"]};
	case 46: {_return = ["Sell Raw","copperu","Sell your unprocessed goods here"]};
	case 47: {_return = ["Sell Processed Goods","processed","Sell your processed goods here"]};
	case 48: {_return = ["Capture Gang Hideout","gang","Capture the nearby gang area"]};
	case 49: {_return = ["Process Weed","gang","Process your weed here"]};
	case 50: {_return = ["Process Heroin","gang","Process your heroin here"]};
	case 51: {_return = ["Process Cocaine","gang","Process your cocaine here"]};
	case 52: {_return = ["Drug Training","gang","Purchase your drug processing training here"]};
	case 53: {_return = ["Illegal Goods Dealer","gang","Sell your illegal goods such as drugs and stolen relics here"]};
	case 54: {_return = ["Gang Items","gang","Buy your gang inventory items here"]};
	case 55: {_return = ["Retrieve Garaged Vehicle","carShop","Retrieve your garaged vehicles here"]};
	case 56: {_return = ["Store Vehicle","carShop","Store your vehicle in your garage here"]};
	case 57: {_return = ["Rebel Weapons","rebelLargeGun","Purchase your rebel weapons here"]};
	case 58: {_return = ["Rebel Licenses","rebelLargeGun","Purchase your rebel trainings here"]};
	case 59: {_return = ["Rebel Large Weapons","rebelLargeGun","Purchase your large rebel weapons here"]};
	case 60: {_return = ["Rebel KOS Weapons","rebelLargeGun","Purchase your KOS rebel weapons here"]};
	case 61: {_return = ["Rebel Vehicles","carShop","Purchase your Rebel vehicles here"]};
	case 62: {_return = ["Armed Rebel Vehicles","rebVeh","Purchase your Armed Rebel vehicles here"]};
	case 63: {_return = ["Rebel Attachments","scope","Purchase attachments for your rebel weapons here"]};
	case 64: {_return = ["Gang Weapons","gunAdv","Illegal low caliber weapons are bought here"]};
	case 65: {_return = ["Gang Vehicles","gang","Get your gang vehicles here"]};
	case 66: {_return = ["Polish Relics","gang","Polish your relics here to prepare them for selling"]};
	case 67: {_return = ["Gas Station Store","market","Buy vehicle related items here"]};
	case 68: {_return = ["Rob Gas Station","robber","Rob the gas station for money"]};
	case 69: {_return = ["Treat Sickness","medic","Treat any sickness you may have"]};
	case 70: {_return = ["Rob Hospital (Chemicals)","robber","Rob the hospital for chemicals"]};
	case 71: {_return = ["Rob Hospital (Cash)","robber","Rob the hospital for cash"]};
	case 72: {_return = ["Rebel Items","market","Items for Rebels"]};
	case 73: {_return = ["Rebel Clothing","civClothing","Rebel styled uniforms"]};
	case 74: {_return = ["Rebel Headgear","civHats","Rebel styled headgear"]};
	case 75: {_return = ["Rebel Glasses","civGlasses","Rebel styled glasses"]};
	case 76: {_return = ["Rebel Vests","civBackpack","Rebel styled vest"]};
	case 77: {_return = ["Rebel Backpacks","civBackpack","Rebel styled backpacks"]};
	case 78: {_return = ["Process Meth","Gang","Process crystal Meth"]};
	case 79: {_return = ["Drug Convoy","Gang","Begin a Drug Convoy"]};
	case 80: {_return = ["Weapons Convoy","Gang","Begin a Weapons Convoy"]};
	case 81: {_return = ["Rebel Item Trader","Gang","Trade your illegal Items for cash here"]};
	case 82: {_return = ["Police Transport","carShop","Transport to other police HQ's"]};
	case 83: {_return = ["Police Air Vehicles","airShop","Buy your police Air Vehicles here"]};
	case 84: {_return = ["Air Vehicle Garage","airShop","Retrieve vehicles from your air garage here"]};
	case 85: {_return = ["Buy Real Estate","atm","Purchase an investment property to boost your pay-checks"]};
	case 86: {_return = ["Boat Garage","boatShop","Retrieve your stored boats here"]};
	case 87: {_return = ["Crop Dusting","airShop","Begin your crop dusting jobs here"]};
	case 88: {_return = ["Jobs Depot","goldBar","A place to get a job as a civilian"]};
	case 89: {_return = ["Evict Gang","gang","Evict the owners of this gang hideout"]};
	case 90: {_return = ["Police Convoys","truckShop","Start a police convoy mission"]};
	case 91: {_return = ["Vehicle Upgrades","repairKit","Upgrade your vehicles here"]};
	case 92: {_return = ["Police Locker","vehLocker","Store and retrieve items from your police locker"]};
	case 93: {_return = ["Gun License","gun","Civilian Legal Weapons license"]};
	case 94: {_return = ["Retrieve MCU","mcu","Retrieve the police Mobile Command Unit vehicle"]};
	case 95: {_return = ["Medic Vehicles","carShop","Buy your Medic vehicles here"]};
	case 96: {_return = ["Mechanic Vehicles","mechanic","Buy your Mechanic vehicles here"]};
	case 97: {_return = ["Rebel Kit (Sniper)","gang","Use this to quickly buy your rebel inventory gear and fit Stun Armour"]};
	case 98: {_return = ["Rebel Kit (General)","gang","Use this to quickly buy your rebel inventory gear and fit Stun Armour"]};
	case 99: {_return = ["Store the MCU","mcu","Store the MCU here"]};
	case 100: {_return = ["Chop Shop","gang","Chop a nearby vehicle for money"]};
	case 101: {_return = ["Public Transport","bus","Use the bus to get around Altis quick and cheaply"]};
	case 102: {_return = ["Rebel Missions","gang","Begin Rebel Missions here"]};
	case 103: {_return = ["Pod Shop","pods","Buy your cargo pods here"]};
	case 104: {_return = ["Blueprints","blueprint","Purchase your blue prints here, detailing the needed materials to craft items"]};
	case 105: {_return = ["Process Lumber","woodu","Purchase your lumber here and either sell it or use it at the factory"]};
	case 106: {_return = ["Craft Vehicle Items","vehRepair","Craft your vehicle upgrade related items here"]};
	case 107: {_return = ["Craft Ingredients","defuse","Craft your required ingredients here"]};
	case 108: {_return = ["Sell Ingredients","market","Sell left over Ingredients here"]};
	case 109: {_return = ["Sell Items","hitech","Sell crafted items here"]};
	case 110: {_return = ["Bribe Dealer","beating","Bribe the dealer for the drug prices"]};
	case 111: {_return = ["Craft Weapon Items","gunAdv","Craft your weapon related items here"]};
	case 112: {_return = ["Lower Truck Level","mdown","Lower your trucking level here to re-do earlier missions"]};
	case 113: {_return = ["Vehicle Paint Shop","carShop","Paint your vehicles here"]};
	case 114: {_return = ["Play Lotto","spyDocs","Purchase your lotto ticket here"]};
	case 115: {_return = ["Building Shop","buildingBox","Purchase building equipment here"]};
	case 116: {_return = ["Pack Box","buildingBox","Pack the box and all equipment bought from it"]};
	case 117: {_return = ["Rearm Vehicles","vehAmmo","Rearm all nearby vehicles"]};
	case 118: {_return = ["Insurance Broker","goldBar","Purchase insurance policies here"]};
	case 119: {_return = ["Security Items","market","Purchase virtual items here"]};
	case 120: {_return = ["Security Vehicles","carShop","Purchase vehicles here"]};
	case 121: {_return = ["Security Weapons","gunAdv","Purchase weapons here"]};
	case 122: {_return = ["Security Weapons","gunAdv","Purchase weapons here"]};
	case 164: {_return = ["Security Attachments","scope","Purchase security attachments here"]};
	case 123: {_return = ["Security Vehicles","carShop","Purchase vehicles here"]};
	case 124: {_return = ["Security Clothing","civClothing","Buy your security clothing here"]};
	case 125: {_return = ["Security Kit","market","Purchase a Security Kit"]};
	case 126: {_return = ["Hire a Lawyer","lawyer","Hire a lawyer in an attempt to have your prison sentence reduced"]};
	case 127: {_return = ["Police Boat Shop","boatShop","Buy police sea vehicles here"]};
	case 128: {_return = ["Clothing Retexture Shop","civClothing","Retexture your clothing here"]};
	case 129: {_return = ["Vehicle Retexture Shop","carShop","Retexture your vehicle here"]};
	case 130: {_return = ["Rebel Token Shop","gang","Use your Rebel Tokens to buy Rebel Items here"]};
	case 131: {_return = ["Process Wheat","wheatp","Bake bread using your wheat to sell"]};
	case 132: {_return = ["Purchase ten police lives","medic","Purchase ten police lives to stop you having your gear wiped"]};
	case 133: {_return = ["Begin Police Patrol","\a3\ui_f\data\gui\cfg\Ranks\sergeant_gs.paa","Begin your police patrol missions here"]};
	case 134: {_return = ["Base Upgrades","gang","Purchase Base Upgrades"]};
	case 135: {_return = ["Plane Missions","airShop","Plane Missions"]};
	case 136: {_return = ["ID Convoy","Gang","Begin a Fake ID Convoy"]};
	case 137: {_return = ["Mechanic Missions","repairKit","Begin a Mechanic Mission"]};
	case 138: {_return = ["Deliver Human Remains","gang","Deliver collected human remains"]};
	case 139: {_return = ["Medic Missions","goldBar","Begin Medic Missions"]};
	case 140: {_return = ["Medic Transport","airShop","Medic Quick Transport"]};
	case 141: {_return = ["Token Missions","gang","Begin a random token mission"]};
	case 142: {_return = ["Air Taxi Missions","airShop","Begin a Air Taxi mission"]};
	case 143: {_return = ["Water Taxi Missions","boatShop","Begin a Water Taxi mission"]};
	case 144: {_return = ["Water Drugs Convoy","boatShop","Begin a water drug convoy mission"]};
	case 145: {_return = ["Water Weapons Convoy","boatShop","Begin a Water weapons convoy mission"]};
	case 146: {_return = ["Retrieve Sea MCU","mcu","Retrieve the police Sea Mobile Command Unit vehicle"]};
	case 147: {_return = ["Clothing Shop","civClothing","Buy your clothing here"]};
	case 148: {_return = ["Whitelist Civilian Boat Shop","boatShop","Buy Whitelist civilian sea vehicles here"]};
	case 155: {_return = ["Random Loadout","gang","Purchase a random loadout with clan funds"]};
	case 156: {_return = ["All Attachments","scope","All available attachments can be bought here"]};
	case 157: {_return = ["All Facegear","civGlasses","All available facegear can be bought here"]};
	case 158: {_return = ["Token Weapons Shop","rebelLargeGun","All available weapons for tokens are bought here"]};
	case 159: {_return = ["Quest Prestige","truckShop","Prestige your quest line once you have completed it"]};
	case 160: {_return = ["Realistic Mode","spyDocs","Switch to, or from realistic mode"]};
	case 161: {_return = ["Token Weapons Shop Advanced","rebelLargeGun","All available weapons for tokens are bought here"]};
	case 162: {_return = ["Token Items Shop Advanced","rebelLargeGun","All available items for tokens are bought here"]};
	case 163: {_return = ["Retrieve Impounded Vehicle","carShop","Retrieve your impounded vehicles here"]};
	case 165: {_return = ["All Headgear","civHats","All available headgear can be bought here"]};
	case 166: {_return = ["Special Rental Vehicles","vehAmmo","Rent armed vehicles that come with upgrades here"]};
};

_return;