/*
	File: fn_varToStr.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Takes the long-name (variable) and returns a display name for our
	virtual item.
*/
private["_var"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
if(_var == "") exitWith {""};

switch (_var) do
{
	//Virtual Inventory Items
	case "life_inv_oilu": {(localize "STR_Item_OilU")};
	case "life_inv_heroinu": {(localize "STR_Item_HeroinU")};
	case "life_inv_heroinp": {(localize "STR_Item_HeroinP")};
	case "life_inv_cannabis": {(localize "STR_Item_Cannabis")};
	case "life_inv_marijuana": {(localize "STR_Item_Marijuana")};
	case "life_inv_apple": {(localize "STR_Item_Apple")};
	case "life_inv_rabbit": {(localize "STR_Item_RabbitMeat")};
	case "life_inv_salema": {(localize "STR_Item_SalemaMeat")};
	case "life_inv_ornate": {(localize "STR_Item_OrnateMeat")};
	case "life_inv_mackerel": {(localize "STR_Item_MackerelMeat")};
	case "life_inv_tuna": {(localize "STR_Item_TunaMeat")};
	case "life_inv_mullet": {(localize "STR_Item_MulletMeat")};
	case "life_inv_catshark": {(localize "STR_Item_CatSharkMeat")};
	case "life_inv_turtle": {(localize "STR_Item_TurtleMeat")};
	case "life_inv_fishingpoles": {(localize "STR_Item_FishingPole")};
	case "life_inv_water": {(localize "STR_Item_WaterBottle")};
	case "life_inv_coffee": {(localize "STR_Item_Coffee")};
	case "life_inv_turtlesoup": {(localize "STR_Item_TurtleSoup")};
	case "life_inv_donuts": {(localize "STR_Item_Donuts")};
	case "life_inv_fuelE": {(localize "STR_Item_FuelE")};
	case "life_inv_fuelF": {(localize "STR_Item_FuelF")};
	case "life_inv_pickaxe": {(localize "STR_Item_Pickaxe")};
	case "life_inv_copperore": {(localize "STR_Item_CopperOre")};
	case "life_inv_ironore": {(localize "STR_Item_IronOre")};
	case "life_inv_ironr": {(localize "STR_Item_IronIngot")};
	case "life_inv_copperr": {(localize "STR_Item_CopperIngot")};
	case "life_inv_sand": {(localize "STR_Item_Sand")};
	case "life_inv_salt": {(localize "STR_Item_Salt")};
	case "life_inv_saltr": {(localize "STR_Item_SaltR")};
	case "life_inv_glass": {(localize "STR_Item_Glass")};
	case "life_inv_diamond": {(localize "STR_Item_DiamondU")};
	case "life_inv_diamondr": {(localize "STR_Item_DiamondC")};
	case "life_inv_tbacon": {(localize "STR_Item_TBacon")};
	case "life_inv_redgull": {(localize "STR_Item_RedGull")};
	case "life_inv_lockpick": {(localize "STR_Item_Lockpick")};
	case "life_inv_peach": {(localize "STR_Item_Peach")};
	case "life_inv_coke": {(localize "STR_Item_CocaineU")};
	case "life_inv_cokep": {(localize "STR_Item_CocaineP")};
	case "life_inv_spikeStrip": {(localize "STR_Item_SpikeStrip")};
	case "life_inv_rock": {(localize "STR_Item_Rock")};
	case "life_inv_cement": {(localize "STR_Item_CementBag")};
	case "life_inv_goldbar": {(localize "STR_Item_GoldBar")};
	case "life_inv_blastingcharge": {(localize "STR_Item_BCharge")};
	case "life_inv_boltcutter": {(localize "STR_Item_BCutter")};
	case "life_inv_defusekit": {(localize "STR_Item_DefuseKit")};
	case "life_inv_storagesmall": {(localize "STR_Item_StorageBS")};
	case "life_inv_storagebig": {(localize "STR_Item_StorageBL")};
	case "life_inv_bauma": {"Baumaterial"};
	case "life_inv_brenn": {"Brenner"};
	case "life_inv_mais": {"Mais"};
	case "life_inv_zucker": {"Zucker"};
	case "life_inv_schnaps": {"Schnaps"};
	case "life_inv_papier": {"Papier"};
	case "life_inv_flasche": {"Leere Flasche"};
	case "life_inv_dose": {"Leere Dose"};
	case "life_inv_stein": {"Stein"};
	case "life_inv_eisenkugel": {"Rostige Eisenkugel"};
	case "life_inv_holzbrett": {"Kaputtes Holzbrett"};
	case "life_inv_schmuck": {"Antiker Schmuck"};
	case "life_inv_vase": {"Antike Vase"};
	case "life_inv_muenze": {"Antike Muenze"};
	case "life_inv_schaufel": {"Schaufel"};
	case "life_inv_methu": {"Unverarbeitetes Meth"};
    case "life_inv_methp": {"Crystal Meth"};
	case "life_inv_silberu": {"Silbererz"};
    case "life_inv_silberp": {"Silberbarren"};
	case "life_inv_zigarettenu": {"Tabak"};
	case "life_inv_zigarettenp": {"Zigarette"};
	case "life_inv_weinu": {"Traube"};
	case "life_inv_weinp": {"Wein"};
	case "life_inv_sprengstoffu": {"Schwarzpulver"};
	case "life_inv_sprengstoffp": {"Sprengstoff"};
	case "life_inv_zigarrenu": {"Tabak"};
	case "life_inv_zigarrenp": {"Zigarre"};
	case "life_inv_lsdu": {"Frösche"};
	case "life_inv_lsdp": {"LSD"};
	case "life_inv_goldu" : {"Golderz"};
	case "life_inv_goldp" : {"Goldbarren"};
	case "life_inv_sschmuck" : {"Silberschmuck"};
	case "life_inv_gschmuck" : {"Goldschmuck"};
	case "life_inv_barrier" : {"Barrier"};
	case "life_inv_barricade" : {"Barricade"};
	case "life_inv_strahler" : {"Strahler"};
	case "life_inv_bauschaufel" : {"Bauschaufel"};
	case "life_inv_presslufthammer" : {"Presslufthammer"};
	case "life_inv_kerosin" : {"Kerosin"};
	case "life_inv_oilp" : {"Benzin"};
	case "life_inv_zipties": {"Handschellen"};
	case "life_inv_baumwolle": {"Baumwolle"};
	case "life_inv_lauf": {"Lauf"};
	case "life_inv_mantel": {"Mantel"};
	case "life_inv_handgriff": {"Handgriff"};
	case "life_inv_schulterstuetze": {"Schulterstuetze"};
	case "life_inv_verschluss": {"Verschluss"};
	case "life_inv_stahl": {"Stahl"};
	case "life_inv_plastik": {"Plastik"};
	case "life_inv_bplrr": {"Blueprint M320 LRR"};
	case "life_inv_bplynx": {"Blueprint GM6 Lynx"};
	case "life_inv_bpmarten": {"Blueprint Mar-10"};
	case "life_inv_bpzafir": {"Blueprint Zafir"};
	case "life_inv_bpakm": {"Blueprint AKM"};
	case "life_inv_bpak12": {"Blueprint AK-12"};
	case "life_inv_bpspar17": {"Blueprint SPAR-17"};
	case "life_inv_zweibein": {"Zweibein"};
	case "life_inv_kohle": {"Kohle"};
	case "life_inv_bpmk1": {"Blueprint Mk1"};
	case "life_inv_bpmk18": {"Blueprint Mk18"};
	case "life_inv_bpmk14": {"Blueprint Mk14"};
	case "life_inv_bpweste4": {"Blueprint Weste St. 4"};
	case "life_inv_lagerkiste": {"Lagerhallenkiste"};
	case "life_inv_kies": {"Kies"};
	case "life_inv_xtc": {"Liquid Ecstasy"};
	case "life_inv_sense": {"7th Sense"};
	case "life_inv_margarita": {"Pizza Margarita"};
	case "life_inv_calzone": {"Pizza Salami"};
	case "life_inv_parkticket": {"Parkticket"};
	case "life_inv_usb": {"USB-Stick"};
	case "life_inv_megaphone": {"Megaphone Ole"};
	
	
	//License Block
	case "license_civ_driver": {(localize "STR_License_Driver")};
	case "license_civ_air": {(localize "STR_License_Pilot")};
	case "license_civ_air2": {"Pilotentraining 2"};
	case "license_civ_heroin": {(localize "STR_License_Heroin")};
	case "license_civ_oil": {(localize "STR_License_Oil")};
	case "license_civ_dive": {(localize "STR_License_Diving")};
	case "license_civ_boat": {(localize "STR_License_Boat")};
	case "license_civ_gun": {(localize "STR_License_Firearm")};
	case "license_cop_air": {(localize "STR_License_Pilot")};
	case "license_cop_swat": {"S.R.T Schulung"};
	case "license_cop_cg": {(localize "STR_License_CG")};
	case "license_cop_adf": {"DEA Schulung"};
	case "license_cop_mrsf": {"MRSF"};
	case "license_civ_rebel": {(localize "STR_License_Rebel")};
	case "license_civ_bm": {"Schwarzmarkt Lizenz"};
	case "license_civ_truck": {(localize "STR_License_Truck")};
	case "license_civ_diamond": {(localize "STR_License_Diamond")};
	case "license_civ_copper": {(localize "STR_License_Copper")};
	case "license_civ_iron": {(localize "STR_License_Iron")};
	case "license_civ_sand": {(localize "STR_License_Sand")};
	case "license_civ_salt": {(localize "STR_License_Salt")};
	case "license_civ_coke": {(localize "STR_License_Cocaine")};
	case "license_civ_marijuana": {(localize "STR_License_Marijuana")};
	case "license_civ_cement": {(localize "STR_License_Cement")};
	case "license_civ_arch": {"Archäologieschein"};
	case "license_med_air": {(localize "STR_License_Pilot")};
	case "license_civ_home": {(localize "STR_License_Home")};
	case "license_civ_meth": {"Meth Training"};
	case "license_civ_sense": {"7th Sense Training"};
	case "license_civ_silber": {"Silber Lizenz"};
	case "license_civ_zigaretten": {"Zigaretten Lizenz"};
	case "license_civ_wein": {"Winzer Lizenz"};
	case "license_civ_sprengstoff": {"Sprengstoff Training"};
	case "license_civ_zigarren": {"Zigarren Training"};
	case "license_civ_lsd": {"LSD Training"};
	case "license_civ_gold": {"Gold Lizenz"};
	case "license_civ_sschmuck": {"Silberschmuck Lizenz"};
	case "license_civ_gschmuck": {"Goldschmuck Lizenz"};
	case "license_civ_dutyfree": {"Duty Free Lizenz"};
	case "license_civ_luftfracht": {"Luftfrachtschein"};
	case "license_civ_fracht": {"Frachtschein"};
	case "license_civ_aufenthalt": {"Aufenthaltsgenehmigung"};
	case "license_civ_arbeitsgenehmigung": {"Arbeitsgenehmigung"}; 
	case "license_civ_muell": {"Müllsortier Lizenz"};
	case "license_civ_whinc": {"Warehouse Inc"};
	case "license_civ_zafir": {"Zafir Bauanleitung"};
	case "license_civ_marten": {"MAR-10 Bauanleitung"};
	case "license_civ_lynx": {"Lynx Bauanleitung"};
	case "license_civ_lrr": {"M320 LRR Bauanleitung"};
	case "license_civ_plastik": {"Plastik Lizenz"};
	case "license_civ_stahl": {"Stahl Lizenz"};
	case "license_civ_mk14": {"Mk14 Bauanleitung"};
	case "license_civ_mk18": {"Mk18 Bauanleitung"};
	case "license_civ_akm": {"AKM Bauanleitung"};
	case "license_civ_ak12": {"AK-12 Bauanleitung"};
	case "license_civ_spar17": {"SPAR-17 Bauanleitung"};
	case "license_civ_mk1": {"Mk1 Bauanleitung"};
	case "license_civ_weste4": {"Weste St. 4 Bauanleitung"};
	case "license_civ_lotto": {"Lotto Mitarbeiter"};
	case "license_civ_mrsf": {"Marine Recon (M.R.S.F)"};
	case "license_civ_pizza": {"Pizza Angestellter"};
	case "license_civ_cc": {"Crenshaw Crew"};
};
