class Socket_Reciever {
    tag = "SOCK";
    class SQL_Socket {
        file = "core\session";
        class dataQuery {};
        class insertPlayerInfo {};
        class requestReceived {};
        class syncData {};
        class updatePartial {};
        class updateRequest {};
    };
};

class Life_Client_Core {
    tag = "life";

    class Master_Directory {
        file = "core";
        class initCiv {};
        class initCop {};
        class initMedic {};
        class setupActions {};
        class setupEVH {};
        class survival {};
        class welcomeNotification {};
    };
    
    class CellPhone {
        file = "core\cellphone";
        class cellPhoneCheck {};
        class setupCellPhone {};
        class messagesMenu {};
        class lbChanged {};
        class deleteMessage {};
        class replyMessage {};
    };

    class Actions {
        file = "core\actions";
        class arrestAction {};
        class buyLicense {};
        class captureHideout {};
        class catchFish {};
        class dpFinish {};
        class dropFishingNet {};
        class escortAction {};
        class gather {};
        class getDPMission {};
        class gutAnimal {};
        class healHospital {};
        class impoundAction {};
        class mine {};
        class newsBroadcast {};
        class packupSpikes {};
        class pickupItem {};
        class pickupMoney {};
        class postBail {};
        class processAction {};
        class pulloutAction {};
        class putInCar {};
        class removeContainer {};
        class repairTruck {};
        class restrainAction {};
        class robAction {};
        class searchAction {};
        class searchVehAction {};
        class seizePlayerAction {};
        class serviceChopper {};
        class stopEscorting {};
        class storeVehicle {};
        class surrender {};
        class ticketAction {};
        class unrestrain {};
        class activateNitro {};
        class civrestrainAction {};
        class unrestrainciv {};
        class patDown {};   
        class seize {};
        class civEscortAction {};
        class removeWeapons {};
        class civStopEscorting {};
        class robShops {};
        class suicideBomb {};
        class jaws {};
        class pickupItem2 {};
        class pushVehicle {};
        class ch7Broadcast {};
        class gatherMetal {};
        class zoneGather {};
        class lsdGather {};
        class gatherDrugs {};
        class createEvidence {};
        class destroyEvidence {};
        class gatherEvidence {};
    };

    class BountyHunters {
            file = "core\BountyHunters";
            class bountyAddMenu {};
            class bountyAddP {};
            class bountyBuy {};
            class bountyGrab {};
            class bountyHunterReceive {};
            class bountyInfo {};
            class bountyKill {};
            class bountyList {};
            class bountyMenu {};
            class markers {};
    };

    class DynMarket
    {
        file = "core\DynMarket";
        class bought {};
        class update {};
        class DisplayPrices {};
        class LoadIntoListbox {};
        class ForcePrice {};
        class DYNMARKET_getPrice {};
    };

    class CopPlaceables {       
        file = "core\cop\placeables";       
        class placeablesInit {};        
        class placeablesMenu {};        
        class placeablesRemoveAll {};       
        class placeablePlace {};        
        class placeableCancel {};       
        class placeablesPlaceComplete {};   
    };

    class CopPlaceablesMEDIC
    {
        file = "core\medical\MedicPlaceables";
        class placeablesInitMEDIC {};
        class placeablesMenuMEDIC {};
        class placeablesRemoveAllMEDIC {};
        class placeablePlaceMEDIC {};
        class placeableCancelMEDIC {};
        class placeablesPlaceCompleteMEDIC {};
    };

class Admin
    {
        file = "core\admin";
        class admininfo {};
        class adminid {};
        class admingetID {};
        class adminMenu {};
        class adminQuery {};
        class adminSpectate {};
        class adminTeleport {};
        class adminTpHere {};
        class adminUnrestrain {};
        class adminRestrain {};
        class tpToPlayer {};
        class adminTpTo {};
        class adminDeleteVehicle {};
        class adminDebugCon {};
        class adminCompensate {};
        class adminGodMode {};
        class adminFreeze {};
        class adminMarkers {};
        class adminATM {};
        class adminRevive {};
        class adminStealth {};
        class adminTpInFront {};
        class adminRide {};
        class shutdownMessage {};
    };

    class Civilian {
        file = "core\civilian";
        class civLoadout {};
        class civMarkers {};
        class demoChargeTimer {};
        class freezePlayer {};
        class jail {};
        class jailMe {};
        class knockedOut {};
        class knockoutAction {};
        class removeLicenses {};
        class robPerson {};
        class robReceive {};
        class tazed {};
        class civInteractionMenu {};
        class civrestrain {};
        class crashTackled {};
        class tackleAction {};
        class nitroSound {};
        class lockpickSound {};
        class civInteractionMenuZip {};
        class allahSound {};
        class beepSound {};
        class bankalarmSound {};
        class gatherZone {};
        class initLaser {};
        class laserJoin {};
    };

    class Config {
        file = "core\config";
        class houseConfig {};
        class itemWeight {};
        class vehicleAnimate {};
        class vehicleWeightCfg {};
    };

    class Cop {
        file = "core\cop";
        class bountyReceive {};
        class containerInvSearch {};
        class copInteractionMenu {};
        class copLights {};
        class copLoadout {};
        class copMarkers {};
        class copSearch {};
        class copSiren {};
        class doorAnimate {};
        class fedCamDisplay {};
        class licenseCheck {};
        class licensesRead {};
        class questionDealer {};
        class radar {};
        class repairDoor {};
        class restrain {};
        class searchClient {};
        class seizeClient {};
        class sirenLights {};
        class spikeStripEffect {};
        class ticketGive {};
        class ticketPaid {};
        class ticketPay {};
        class ticketPrompt {};
        class vehInvSearch {};
        class wantedGrab {};
        class showArrestDialog {};
        class arrestDialog_Arrest {};
        class airhorn {};
        class warning {};
        class warning2 {};
        class warning3 {};
        class copSplit {};
        class copSplitTransport {};
    };

    class Dialog_Controls {
        file = "dialog\function";
        class bankDeposit {};
        class bankTransfer {};
        class bankWithdraw {};
        class displayHandler {};
        class gangDeposit {};
        class gangWithdraw {};
        class garageLBChange {};
        class impoundMenu {};
        class progressBar {};
        class safeFix {};
        class safeInventory {};
        class safeOpen {};
        class safeTake {};
        class sellGarage {};
        class setMapPosition {};
        class spawnConfirm {};
        class spawnMenu {};
        class spawnPointCfg {};
        class spawnPointSelected {};
        class unimpound {};
        class vehicleGarage {};
        class wireTransfer {};
    };

    class Functions {
        file = "core\functions";
        class AAN {};
        class accType {};
        class actionKeyHandler {};
        class animSync {};
        class calWeightDiff {};
        class clearVehicleAmmo {};
        class dropItems {};
        class escInterupt {};
        class fetchCfgDetails {};
        class fetchDeadGear {};
        class fetchVehInfo {};
        class isDamaged {};
        class giveDiff {};
        class handleDamage {};
        class handleInv {};
        class handleItem {};
        class hideObj {};
        class hudSetup {};
        class hudUpdate {};
        class inventoryClosed {};
        class inventoryOpened {};
        class isUIDActive {};
        class keyHandler {};
        class loadDeadGear {};
        class loadGear {};
        class nearATM {};
        class nearestDoor {};
        class nearUnits {};
        class numberText {};
        class onFired {};
        class onTakeItem {};
        class playerSkins {};
        class playerTags {};
        class postNewsBroadcast {};
        class pullOutVeh {};
        class pushObject {};
        class receiveItem {};
        class receiveMoney {};
        class revealObjects {};
        class saveGear {};
        class searchPosEmpty {};
        class simDisable {};
        class stripDownPlayer {};
        class tazeSound {};
        class teleport {};
        class whereAmI {};
        class nearestSound {};
        class seatbelt {};
        class pickupitems {};
        class mouseUpHandler {};
        class mouseDownHandler {};
        class loggedOut {};
        class showBroadcast {};
        class phoneCall {};
        class phoneEnd {};
        class destroyComms {};
        class destroyedComms {};
        class panicMarker {};
        class speaking {}; 
        class handleTagged {};
        class ryn_message {};
    };

    class Gangs {
        file = "core\gangs";
        class createGang {};
        class gangCreated {};
        class gangDisband {};
        class gangDisbanded {};
        class gangInvite {};
        class gangInvitePlayer {};
        class gangKick {};
        class gangLeave {};
        class gangMenu {};
        class gangNewLeader {};
        class gangUpgrade {};
        class initGang {};
    };

    class Housing {
        file = "core\housing";
        class buyHouse {};
        class buyHouseGarage {};
        class containerMenu {};
        class copBreakDoor {};
        class copHouseOwner {};
        class garageRefund {};
        class getBuildingPositions {};
        class houseMenu {};
        class initHouses {};
        class lightHouse {};
        class lightHouseAction {};
        class lockHouse {};
        class lockupHouse {};
        class placeContainer {};
        class PlayerInBuilding {};
        class raidHouse {};
        class sellHouse {};
        class sellHouseGarage {};
    };

    class Items {
        file = "core\items";
        class blastingCharge {};
        class boltcutter {};
        class defuseKit {};
        class flashbang {};
        class jerrycanRefuel {};
        class jerryRefuel {};
        class lockpick {};
        class placestorage {};
        class spikeStrip {};
        class storageBox {};
        class cprkit {};
        class nitro {};
        class weed {};
        class lsd {};
        class panicButton {};
    };

    class Medical_System {
        file = "core\medical";
        class deathScreen {};
        class medicLights {};
        class medicLoadout {};
        class medicMarkers {};
        class medicRequest {};
        class medicSiren {};
        class medicSirenLights {};
        class onPlayerKilled {};
        class onPlayerRespawn {};
        class requestMedic {};
        class respawned {};
        class revived {};
        class revivePlayer {};
        class cprrevived {};
        class medicEnroute {};
    };

    class Network {
        file = "core\functions\network";
        class broadcast {};
        class corpse {};
        class jumpFnc {};
        class say3D {};
        class setFuel {};
        class soundDevice {};
        class dispatch {};
        class dispatchpanic {};
        class dispatchbank {};
    };

    class Player_Menu {
        file = "core\pmenu";
        class cellphone {};
        class giveItem {};
        class giveMoney {};
        class keyDrop {};
        class keyGive {};
        class keyMenu {};
        class p_openMenu {};
        class p_moneyopenMenu {};
        class p_licencesopenMenu {};
        class p_invopenMenu {};
        class p_updateMenu {};
        class pardon {};
        class removeItem {};
        class s_onChar {};
        class s_onCheckedChange {};
        class s_onSliderChange {};
        class settingsMenu {};
        class updateViewDistance {};
        class useItem {};
        class wantedAddP {};
        class wantedInfo {};
        class wantedList {};
        class wantedMenu {};
        class cell_call {};
        class radioPhone {};
        class licences {};
        class inv {};
        class money {};
    };

    class Shops {
        file = "core\shops";
        class atmMenu {};
        class buyClothes {};
        class changeClothes {};
        class chopShopMenu {};
        class chopShopSelection {};
        class chopShopSell {};
        class clothingFilter {};
        class clothingMenu {};
        class fuelLBchange {};
        class fuelStatOpen {};
        class levelCheck {};
        class vehicleShop3DPreview {};
        class vehicleShopBuy {};
        class vehicleShopEnd3DPreview {};
        class vehicleShopInit3DPreview {};
        class vehicleShopLBChange {};
        class vehicleShopMenu {};
        class virt_buy {};
        class virt_menu {};
        class virt_sell {};
        class virt_update {};
        class weaponShopAccs {};
        class weaponShopBuySell {};
        class weaponShopFilter {};
        class weaponShopMags {};
        class weaponShopMenu {};
        class weaponShopSelection {};
        class BJbet {};
        class BJhit {};
        class BJstay {};
        class blackjack {};
        class slotSpin {};
        class slotmachine {};
    };

    class Vehicle {
        file = "core\vehicle";
        class addVehicle2Chain {};
        class colorVehicle {};
        class deviceMine {};
        class FuelRefuelcar {};
        class fuelStore {};
        class fuelSupply {};
        class lockVehicle {};
        class openInventory {};
        class vehiclecolor3DRefresh {};
        class vehicleOwners {};
        class vehicleWeight {};
        class vehInventory {};
        class vehStoreItem {};
        class vehTakeItem {};
        class vInteractionMenu {};
        class turnSignal {};
        class vehTakeAllItem {};
        class vehStoreAllItem {};
    };
};