private["_val","_unit","_tax"];
_val = parseNumber(ctrlText 2702);
_unit = call compile format["%1",(lbData[2703,(lbCurSel 2703)])];
if(isNull _unit) exitWith {};
if((lbCurSel 2703) == -1) exitWith {hint localize "STR_ATM_Noneselected"};
if(isNil "_unit") exitWith {hint localize "STR_ATM_DoesntExist"};
if(_val > 999999) exitWith {hint localize "STR_ATM_TransferMax";};
if(_val < 0) exitwith {};
if(!([str(_val)] call life_fnc_isnumeric)) exitWith {hint localize "STR_ATM_notnumeric"};
if(_val > compte_banque) exitWith {hint localize "STR_ATM_NotEnough"};
//_tax = [_val] call life_fnc_taxRate;
_tax = round(_val / 15);
if((_val + _tax) > compte_banque) exitWith {hint format[localize "STR_ATM_SentMoneyFail",_val,_tax]};
compte_banque = compte_banque - (_val + _tax);
[[_val,profileName],"TON_fnc_clientWireTransfer",_unit,false] spawn life_fnc_MP;
[[player, _unit, _val, 0, compte_banque, argent_liquide],"TON_fnc_handleDBLog",false] spawn life_fnc_MP; 
[] call life_fnc_atmMenu;
hint format[localize "STR_ATM_SentMoneySuccess",[_val] call life_fnc_numberText,_unit getVariable["realname",name _unit],[_tax] call life_fnc_numberText];
[1] call SOCK_fnc_updatePartial;